/* ====== Minna no Nihongo I (L7–25) and II (L26–50) vocabulary ======
   Appended to WORDS from data.js. Best-effort standard lists with
   English / Russian / Armenian meanings. Flag any wrong entry to fix it. */
WORDS.push(
/* ---- Minna I, Lesson 7 ---- */
{b:"minna1",l:7,jp:"切ります",rd:"きります",ro:"kirimasu",en:"to cut",ru:"резать",hy:"կտրել",img:""},
{b:"minna1",l:7,jp:"送ります",rd:"おくります",ro:"okurimasu",en:"to send",ru:"посылать",hy:"ուղարկել",img:""},
{b:"minna1",l:7,jp:"あげます",rd:"あげます",ro:"agemasu",en:"to give",ru:"давать",hy:"տալ",img:""},
{b:"minna1",l:7,jp:"もらいます",rd:"もらいます",ro:"moraimasu",en:"to receive",ru:"получать",hy:"ստանալ",img:""},
{b:"minna1",l:7,jp:"貸します",rd:"かします",ro:"kashimasu",en:"to lend",ru:"одалживать",hy:"փոխ տալ",img:""},
{b:"minna1",l:7,jp:"借ります",rd:"かります",ro:"karimasu",en:"to borrow",ru:"брать в долг",hy:"փոխ առնել",img:""},
{b:"minna1",l:7,jp:"教えます",rd:"おしえます",ro:"oshiemasu",en:"to teach",ru:"учить (кого-то)",hy:"սովորեցնել",img:""},
{b:"minna1",l:7,jp:"習います",rd:"ならいます",ro:"naraimasu",en:"to learn",ru:"учиться",hy:"սովորել",img:""},
{b:"minna1",l:7,jp:"かけます",rd:"かけます",ro:"kakemasu",en:"to make (a phone call)",ru:"звонить",hy:"զանգահարել",img:""},
{b:"minna1",l:7,jp:"手",rd:"て",ro:"te",en:"hand",ru:"рука",hy:"ձեռք",img:"hand"},
{b:"minna1",l:7,jp:"はし",rd:"はし",ro:"hashi",en:"chopsticks",ru:"палочки для еды",hy:"չոփսթիք",img:"chopsticks"},
{b:"minna1",l:7,jp:"スプーン",rd:"",ro:"supuun",en:"spoon",ru:"ложка",hy:"գդալ",img:"spoon"},
{b:"minna1",l:7,jp:"ナイフ",rd:"",ro:"naifu",en:"knife",ru:"нож",hy:"դանակ",img:"knife"},
{b:"minna1",l:7,jp:"フォーク",rd:"",ro:"fooku",en:"fork",ru:"вилка",hy:"պատառաքաղ",img:"fork"},
{b:"minna1",l:7,jp:"はさみ",rd:"はさみ",ro:"hasami",en:"scissors",ru:"ножницы",hy:"մկրատ",img:"scissors"},
{b:"minna1",l:7,jp:"パソコン",rd:"",ro:"pasokon",en:"personal computer",ru:"компьютер",hy:"համակարգիչ",img:"computer"},
{b:"minna1",l:7,jp:"手紙",rd:"てがみ",ro:"tegami",en:"letter",ru:"письмо",hy:"նամակ",img:"letter_obj"},
{b:"minna1",l:7,jp:"レポート",rd:"",ro:"repooto",en:"report",ru:"доклад, отчёт",hy:"զեկույց",img:"letter_obj"},
{b:"minna1",l:7,jp:"写真",rd:"しゃしん",ro:"shashin",en:"photograph",ru:"фотография",hy:"լուսանկար",img:"photograph"},
{b:"minna1",l:7,jp:"花",rd:"はな",ro:"hana",en:"flower",ru:"цветок",hy:"ծաղիկ",img:"flower"},
{b:"minna1",l:7,jp:"シャツ",rd:"",ro:"shatsu",en:"shirt",ru:"рубашка",hy:"վերնաշապիկ",img:"shirt"},
{b:"minna1",l:7,jp:"プレゼント",rd:"",ro:"purezento",en:"present, gift",ru:"подарок",hy:"նվեր",img:"gift"},
{b:"minna1",l:7,jp:"荷物",rd:"にもつ",ro:"nimotsu",en:"luggage, parcel",ru:"багаж",hy:"բեռ",img:"luggage"},
{b:"minna1",l:7,jp:"お金",rd:"おかね",ro:"okane",en:"money",ru:"деньги",hy:"փող",img:"money"},
{b:"minna1",l:7,jp:"切符",rd:"きっぷ",ro:"kippu",en:"ticket",ru:"билет",hy:"տոմս",img:"ticket"},
{b:"minna1",l:7,jp:"父",rd:"ちち",ro:"chichi",en:"(my) father",ru:"(мой) отец",hy:"(իմ) հայրը",img:"father"},
{b:"minna1",l:7,jp:"母",rd:"はは",ro:"haha",en:"(my) mother",ru:"(моя) мать",hy:"(իմ) մայրը",img:"mother"},
{b:"minna1",l:7,jp:"もう",rd:"もう",ro:"mou",en:"already",ru:"уже",hy:"արդեն",img:""},
{b:"minna1",l:7,jp:"まだ",rd:"まだ",ro:"mada",en:"not yet",ru:"ещё нет",hy:"դեռ",img:""},
/* ---- Minna I, Lesson 8 ---- */
{b:"minna1",l:8,jp:"きれい",rd:"きれい",ro:"kirei",en:"beautiful, clean",ru:"красивый, чистый",hy:"գեղեցիկ, մաքուր",img:""},
{b:"minna1",l:8,jp:"静か",rd:"しずか",ro:"shizuka",en:"quiet",ru:"тихий",hy:"հանգիստ",img:""},
{b:"minna1",l:8,jp:"にぎやか",rd:"にぎやか",ro:"nigiyaka",en:"lively",ru:"оживлённый",hy:"աշխույժ",img:""},
{b:"minna1",l:8,jp:"有名",rd:"ゆうめい",ro:"yuumei",en:"famous",ru:"известный",hy:"հայտնի",img:""},
{b:"minna1",l:8,jp:"親切",rd:"しんせつ",ro:"shinsetsu",en:"kind",ru:"добрый",hy:"բարի",img:""},
{b:"minna1",l:8,jp:"元気",rd:"げんき",ro:"genki",en:"healthy, energetic",ru:"здоровый, бодрый",hy:"առողջ, եռանդուն",img:""},
{b:"minna1",l:8,jp:"暇",rd:"ひま",ro:"hima",en:"free (time)",ru:"свободный (о времени)",hy:"ազատ (ժամանակ)",img:""},
{b:"minna1",l:8,jp:"便利",rd:"べんり",ro:"benri",en:"convenient",ru:"удобный",hy:"հարմար",img:""},
{b:"minna1",l:8,jp:"すてき",rd:"すてき",ro:"suteki",en:"nice, wonderful",ru:"прекрасный",hy:"հիանալի",img:""},
{b:"minna1",l:8,jp:"大きい",rd:"おおきい",ro:"ookii",en:"big",ru:"большой",hy:"մեծ",img:""},
{b:"minna1",l:8,jp:"小さい",rd:"ちいさい",ro:"chiisai",en:"small",ru:"маленький",hy:"փոքր",img:""},
{b:"minna1",l:8,jp:"新しい",rd:"あたらしい",ro:"atarashii",en:"new",ru:"новый",hy:"նոր",img:""},
{b:"minna1",l:8,jp:"古い",rd:"ふるい",ro:"furui",en:"old (things)",ru:"старый (о вещах)",hy:"հին",img:""},
{b:"minna1",l:8,jp:"いい",rd:"いい",ro:"ii",en:"good",ru:"хороший",hy:"լավ",img:""},
{b:"minna1",l:8,jp:"悪い",rd:"わるい",ro:"warui",en:"bad",ru:"плохой",hy:"վատ",img:""},
{b:"minna1",l:8,jp:"暑い",rd:"あつい",ro:"atsui",en:"hot (weather)",ru:"жаркий",hy:"շոգ",img:""},
{b:"minna1",l:8,jp:"寒い",rd:"さむい",ro:"samui",en:"cold (weather)",ru:"холодный (о погоде)",hy:"ցուրտ",img:""},
{b:"minna1",l:8,jp:"熱い",rd:"あつい",ro:"atsui",en:"hot (to touch)",ru:"горячий",hy:"տաք",img:""},
{b:"minna1",l:8,jp:"冷たい",rd:"つめたい",ro:"tsumetai",en:"cold (to touch)",ru:"холодный (на ощупь)",hy:"սառը",img:""},
{b:"minna1",l:8,jp:"難しい",rd:"むずかしい",ro:"muzukashii",en:"difficult",ru:"трудный",hy:"դժվար",img:""},
{b:"minna1",l:8,jp:"易しい",rd:"やさしい",ro:"yasashii",en:"easy",ru:"лёгкий",hy:"հեշտ",img:""},
{b:"minna1",l:8,jp:"高い",rd:"たかい",ro:"takai",en:"expensive, high",ru:"дорогой, высокий",hy:"թանկ, բարձր",img:""},
{b:"minna1",l:8,jp:"安い",rd:"やすい",ro:"yasui",en:"cheap",ru:"дешёвый",hy:"էժան",img:""},
{b:"minna1",l:8,jp:"低い",rd:"ひくい",ro:"hikui",en:"low",ru:"низкий",hy:"ցածր",img:""},
{b:"minna1",l:8,jp:"おもしろい",rd:"おもしろい",ro:"omoshiroi",en:"interesting",ru:"интересный",hy:"հետաքրքիր",img:""},
{b:"minna1",l:8,jp:"おいしい",rd:"おいしい",ro:"oishii",en:"delicious",ru:"вкусный",hy:"համեղ",img:""},
{b:"minna1",l:8,jp:"忙しい",rd:"いそがしい",ro:"isogashii",en:"busy",ru:"занятый",hy:"զբաղված",img:""},
{b:"minna1",l:8,jp:"楽しい",rd:"たのしい",ro:"tanoshii",en:"enjoyable",ru:"весёлый, приятный",hy:"հաճելի",img:""},
{b:"minna1",l:8,jp:"白い",rd:"しろい",ro:"shiroi",en:"white",ru:"белый",hy:"սպիտակ",img:"white_color"},
{b:"minna1",l:8,jp:"黒い",rd:"くろい",ro:"kuroi",en:"black",ru:"чёрный",hy:"սև",img:"black_color"},
{b:"minna1",l:8,jp:"赤い",rd:"あかい",ro:"akai",en:"red",ru:"красный",hy:"կարմիր",img:"red_color"},
{b:"minna1",l:8,jp:"青い",rd:"あおい",ro:"aoi",en:"blue",ru:"синий",hy:"կապույտ",img:"blue_color"},
{b:"minna1",l:8,jp:"桜",rd:"さくら",ro:"sakura",en:"cherry blossom",ru:"сакура",hy:"սակուրա",img:""},
{b:"minna1",l:8,jp:"山",rd:"やま",ro:"yama",en:"mountain",ru:"гора",hy:"լեռ",img:"mountain"},
{b:"minna1",l:8,jp:"町",rd:"まち",ro:"machi",en:"town",ru:"город",hy:"քաղաք",img:""},
{b:"minna1",l:8,jp:"食べ物",rd:"たべもの",ro:"tabemono",en:"food",ru:"еда",hy:"սնունդ",img:""},
{b:"minna1",l:8,jp:"所",rd:"ところ",ro:"tokoro",en:"place",ru:"место",hy:"տեղ",img:""},
{b:"minna1",l:8,jp:"とても",rd:"とても",ro:"totemo",en:"very",ru:"очень",hy:"շատ",img:""},
{b:"minna1",l:8,jp:"あまり",rd:"あまり",ro:"amari",en:"not so (with negative)",ru:"не очень",hy:"այնքան էլ ոչ",img:""},
/* ---- Minna I, Lesson 9 ---- */
{b:"minna1",l:9,jp:"わかります",rd:"わかります",ro:"wakarimasu",en:"to understand",ru:"понимать",hy:"հասկանալ",img:""},
{b:"minna1",l:9,jp:"あります",rd:"あります",ro:"arimasu",en:"to have",ru:"иметь",hy:"ունենալ",img:""},
{b:"minna1",l:9,jp:"好き",rd:"すき",ro:"suki",en:"to like",ru:"нравится",hy:"դուր գալ",img:""},
{b:"minna1",l:9,jp:"嫌い",rd:"きらい",ro:"kirai",en:"to dislike",ru:"не нравится",hy:"չհավանել",img:""},
{b:"minna1",l:9,jp:"上手",rd:"じょうず",ro:"jouzu",en:"good at (skillful)",ru:"умелый",hy:"հմուտ",img:""},
{b:"minna1",l:9,jp:"下手",rd:"へた",ro:"heta",en:"poor at (unskillful)",ru:"неумелый",hy:"անհմուտ",img:""},
{b:"minna1",l:9,jp:"料理",rd:"りょうり",ro:"ryouri",en:"cooking, dish",ru:"кулинария, блюдо",hy:"խոհարարություն, ուտեստ",img:""},
{b:"minna1",l:9,jp:"飲み物",rd:"のみもの",ro:"nomimono",en:"drink",ru:"напиток",hy:"ըմպելիք",img:""},
{b:"minna1",l:9,jp:"スポーツ",rd:"",ro:"supootsu",en:"sport",ru:"спорт",hy:"սպորտ",img:""},
{b:"minna1",l:9,jp:"野球",rd:"やきゅう",ro:"yakyuu",en:"baseball",ru:"бейсбол",hy:"բեյսբոլ",img:"baseball"},
{b:"minna1",l:9,jp:"ダンス",rd:"",ro:"dansu",en:"dance",ru:"танец",hy:"պար",img:"dance"},
{b:"minna1",l:9,jp:"音楽",rd:"おんがく",ro:"ongaku",en:"music",ru:"музыка",hy:"երաժշտություն",img:"music"},
{b:"minna1",l:9,jp:"歌",rd:"うた",ro:"uta",en:"song",ru:"песня",hy:"երգ",img:""},
{b:"minna1",l:9,jp:"コンサート",rd:"",ro:"konsaato",en:"concert",ru:"концерт",hy:"համերգ",img:""},
{b:"minna1",l:9,jp:"カラオケ",rd:"",ro:"karaoke",en:"karaoke",ru:"караоке",hy:"կարաոկե",img:"karaoke"},
{b:"minna1",l:9,jp:"歌舞伎",rd:"かぶき",ro:"kabuki",en:"kabuki",ru:"кабуки",hy:"կաբուկի",img:"kabuki"},
{b:"minna1",l:9,jp:"絵",rd:"え",ro:"e",en:"picture, painting",ru:"картина, рисунок",hy:"նկար",img:"picture"},
{b:"minna1",l:9,jp:"字",rd:"じ",ro:"ji",en:"letter, character",ru:"буква, иероглиф",hy:"տառ, գիր",img:"letter_obj"},
{b:"minna1",l:9,jp:"漢字",rd:"かんじ",ro:"kanji",en:"kanji",ru:"кандзи",hy:"կանջի",img:""},
{b:"minna1",l:9,jp:"ひらがな",rd:"ひらがな",ro:"hiragana",en:"hiragana",ru:"хирагана",hy:"հիրագանա",img:""},
{b:"minna1",l:9,jp:"カタカナ",rd:"",ro:"katakana",en:"katakana",ru:"катакана",hy:"կատականա",img:""},
{b:"minna1",l:9,jp:"英語",rd:"えいご",ro:"eigo",en:"English (language)",ru:"английский язык",hy:"անգլերեն",img:""},
{b:"minna1",l:9,jp:"時間",rd:"じかん",ro:"jikan",en:"time",ru:"время",hy:"ժամանակ",img:""},
{b:"minna1",l:9,jp:"用事",rd:"ようじ",ro:"youji",en:"errand, business",ru:"дело",hy:"գործ",img:""},
{b:"minna1",l:9,jp:"約束",rd:"やくそく",ro:"yakusoku",en:"appointment, promise",ru:"обещание, договорённость",hy:"խոստում, պայմանավորվածություն",img:""},
{b:"minna1",l:9,jp:"よく",rd:"よく",ro:"yoku",en:"well, often",ru:"хорошо, часто",hy:"լավ, հաճախ",img:""},
{b:"minna1",l:9,jp:"だいたい",rd:"だいたい",ro:"daitai",en:"mostly, roughly",ru:"в основном",hy:"հիմնականում",img:""},
{b:"minna1",l:9,jp:"たくさん",rd:"たくさん",ro:"takusan",en:"a lot",ru:"много",hy:"շատ",img:""},
{b:"minna1",l:9,jp:"少し",rd:"すこし",ro:"sukoshi",en:"a little",ru:"немного",hy:"մի քիչ",img:""},
{b:"minna1",l:9,jp:"全然",rd:"ぜんぜん",ro:"zenzen",en:"not at all",ru:"совсем не",hy:"ընդհանրապես ոչ",img:""},
{b:"minna1",l:9,jp:"早く",rd:"はやく",ro:"hayaku",en:"early, quickly",ru:"рано, быстро",hy:"շուտ, արագ",img:""},
{b:"minna1",l:9,jp:"どうして",rd:"どうして",ro:"doushite",en:"why",ru:"почему",hy:"ինչու",img:""},
/* ---- Minna I, Lesson 10 ---- */
{b:"minna1",l:10,jp:"います",rd:"います",ro:"imasu",en:"to be (animate)",ru:"быть (о живом)",hy:"լինել (կենդանի)",img:""},
{b:"minna1",l:10,jp:"男の人",rd:"おとこのひと",ro:"otoko no hito",en:"man",ru:"мужчина",hy:"տղամարդ",img:"man"},
{b:"minna1",l:10,jp:"女の人",rd:"おんなのひと",ro:"onna no hito",en:"woman",ru:"женщина",hy:"կին",img:"woman"},
{b:"minna1",l:10,jp:"男の子",rd:"おとこのこ",ro:"otoko no ko",en:"boy",ru:"мальчик",hy:"տղա",img:"boy"},
{b:"minna1",l:10,jp:"女の子",rd:"おんなのこ",ro:"onna no ko",en:"girl",ru:"девочка",hy:"աղջիկ",img:"girl"},
{b:"minna1",l:10,jp:"犬",rd:"いぬ",ro:"inu",en:"dog",ru:"собака",hy:"շուն",img:"dog"},
{b:"minna1",l:10,jp:"猫",rd:"ねこ",ro:"neko",en:"cat",ru:"кошка",hy:"կատու",img:"cat"},
{b:"minna1",l:10,jp:"木",rd:"き",ro:"ki",en:"tree",ru:"дерево",hy:"ծառ",img:""},
{b:"minna1",l:10,jp:"物",rd:"もの",ro:"mono",en:"thing",ru:"вещь",hy:"իր",img:""},
{b:"minna1",l:10,jp:"電池",rd:"でんち",ro:"denchi",en:"battery",ru:"батарейка",hy:"մարտկոց",img:"battery"},
{b:"minna1",l:10,jp:"箱",rd:"はこ",ro:"hako",en:"box",ru:"коробка",hy:"տուփ",img:"box"},
{b:"minna1",l:10,jp:"冷蔵庫",rd:"れいぞうこ",ro:"reizouko",en:"refrigerator",ru:"холодильник",hy:"սառնարան",img:""},
{b:"minna1",l:10,jp:"テーブル",rd:"",ro:"teeburu",en:"table",ru:"стол",hy:"սեղան",img:""},
{b:"minna1",l:10,jp:"ベッド",rd:"",ro:"beddo",en:"bed",ru:"кровать",hy:"մահճակալ",img:""},
{b:"minna1",l:10,jp:"棚",rd:"たな",ro:"tana",en:"shelf",ru:"полка",hy:"դարակ",img:""},
{b:"minna1",l:10,jp:"ドア",rd:"",ro:"doa",en:"door",ru:"дверь",hy:"դուռ",img:""},
{b:"minna1",l:10,jp:"窓",rd:"まど",ro:"mado",en:"window",ru:"окно",hy:"պատուհան",img:""},
{b:"minna1",l:10,jp:"ポスト",rd:"",ro:"posuto",en:"mailbox",ru:"почтовый ящик",hy:"փոստարկղ",img:""},
{b:"minna1",l:10,jp:"ビル",rd:"",ro:"biru",en:"building",ru:"здание",hy:"շենք",img:""},
{b:"minna1",l:10,jp:"公園",rd:"こうえん",ro:"kouen",en:"park",ru:"парк",hy:"զբոսայգի",img:"park"},
{b:"minna1",l:10,jp:"乗り場",rd:"のりば",ro:"noriba",en:"taxi stand, platform",ru:"стоянка, платформа",hy:"կանգառ",img:""},
{b:"minna1",l:10,jp:"上",rd:"うえ",ro:"ue",en:"on, above",ru:"наверху, над",hy:"վրա, վերև",img:""},
{b:"minna1",l:10,jp:"下",rd:"した",ro:"shita",en:"under, below",ru:"под, внизу",hy:"տակ, ներքև",img:""},
{b:"minna1",l:10,jp:"前",rd:"まえ",ro:"mae",en:"front",ru:"перед",hy:"առջև",img:""},
{b:"minna1",l:10,jp:"後ろ",rd:"うしろ",ro:"ushiro",en:"back, behind",ru:"сзади",hy:"հետև",img:""},
{b:"minna1",l:10,jp:"右",rd:"みぎ",ro:"migi",en:"right",ru:"право",hy:"աջ",img:""},
{b:"minna1",l:10,jp:"左",rd:"ひだり",ro:"hidari",en:"left",ru:"лево",hy:"ձախ",img:""},
{b:"minna1",l:10,jp:"中",rd:"なか",ro:"naka",en:"inside",ru:"внутри",hy:"ներսում",img:""},
{b:"minna1",l:10,jp:"外",rd:"そと",ro:"soto",en:"outside",ru:"снаружи",hy:"դրսում",img:""},
{b:"minna1",l:10,jp:"隣",rd:"となり",ro:"tonari",en:"next to",ru:"рядом",hy:"կողքին",img:""},
{b:"minna1",l:10,jp:"近く",rd:"ちかく",ro:"chikaku",en:"near, vicinity",ru:"поблизости",hy:"մոտակայք",img:""},
{b:"minna1",l:10,jp:"間",rd:"あいだ",ro:"aida",en:"between",ru:"между",hy:"միջև",img:""},
/* ---- Minna I, Lesson 11 ---- */
{b:"minna1",l:11,jp:"かかります",rd:"かかります",ro:"kakarimasu",en:"to take (time/money)",ru:"занимать (время/деньги)",hy:"տևել (ժամանակ/գումար)",img:""},
{b:"minna1",l:11,jp:"休みます",rd:"やすみます",ro:"yasumimasu",en:"to rest, take a day off",ru:"отдыхать",hy:"հանգստանալ",img:""},
{b:"minna1",l:11,jp:"一つ",rd:"ひとつ",ro:"hitotsu",en:"one (thing)",ru:"одна штука",hy:"մեկ հատ",img:""},
{b:"minna1",l:11,jp:"二つ",rd:"ふたつ",ro:"futatsu",en:"two (things)",ru:"две штуки",hy:"երկու հատ",img:""},
{b:"minna1",l:11,jp:"三つ",rd:"みっつ",ro:"mittsu",en:"three (things)",ru:"три штуки",hy:"երեք հատ",img:""},
{b:"minna1",l:11,jp:"四つ",rd:"よっつ",ro:"yottsu",en:"four (things)",ru:"четыре штуки",hy:"չորս հատ",img:""},
{b:"minna1",l:11,jp:"五つ",rd:"いつつ",ro:"itsutsu",en:"five (things)",ru:"пять штук",hy:"հինգ հատ",img:""},
{b:"minna1",l:11,jp:"六つ",rd:"むっつ",ro:"muttsu",en:"six (things)",ru:"шесть штук",hy:"վեց հատ",img:""},
{b:"minna1",l:11,jp:"七つ",rd:"ななつ",ro:"nanatsu",en:"seven (things)",ru:"семь штук",hy:"յոթ հատ",img:""},
{b:"minna1",l:11,jp:"八つ",rd:"やっつ",ro:"yattsu",en:"eight (things)",ru:"восемь штук",hy:"ութ հատ",img:""},
{b:"minna1",l:11,jp:"九つ",rd:"ここのつ",ro:"kokonotsu",en:"nine (things)",ru:"девять штук",hy:"ինը հատ",img:""},
{b:"minna1",l:11,jp:"十",rd:"とお",ro:"too",en:"ten (things)",ru:"десять штук",hy:"տասը հատ",img:""},
{b:"minna1",l:11,jp:"いくつ",rd:"いくつ",ro:"ikutsu",en:"how many",ru:"сколько",hy:"քանի հատ",img:""},
{b:"minna1",l:11,jp:"りんご",rd:"りんご",ro:"ringo",en:"apple",ru:"яблоко",hy:"խնձոր",img:"apple"},
{b:"minna1",l:11,jp:"みかん",rd:"みかん",ro:"mikan",en:"mandarin orange",ru:"мандарин",hy:"մանդարին",img:"orange"},
{b:"minna1",l:11,jp:"切手",rd:"きって",ro:"kitte",en:"postage stamp",ru:"почтовая марка",hy:"նամականիշ",img:"stamp"},
{b:"minna1",l:11,jp:"はがき",rd:"はがき",ro:"hagaki",en:"postcard",ru:"открытка",hy:"բացիկ",img:"postcard"},
{b:"minna1",l:11,jp:"封筒",rd:"ふうとう",ro:"fuutou",en:"envelope",ru:"конверт",hy:"ծրար",img:"envelope"},
{b:"minna1",l:11,jp:"外国",rd:"がいこく",ro:"gaikoku",en:"foreign country",ru:"заграница",hy:"արտասահման",img:""},
{b:"minna1",l:11,jp:"時々",rd:"ときどき",ro:"tokidoki",en:"sometimes",ru:"иногда",hy:"երբեմն",img:""},
{b:"minna1",l:11,jp:"一度",rd:"いちど",ro:"ichido",en:"once, one time",ru:"один раз",hy:"մեկ անգամ",img:""},
{b:"minna1",l:11,jp:"だけ",rd:"だけ",ro:"dake",en:"only",ru:"только",hy:"միայն",img:""},
{b:"minna1",l:11,jp:"みんな",rd:"みんな",ro:"minna",en:"everyone, all",ru:"все",hy:"բոլորը",img:""},
/* ---- Minna I, Lesson 12 ---- */
{b:"minna1",l:12,jp:"簡単",rd:"かんたん",ro:"kantan",en:"simple, easy",ru:"простой",hy:"պարզ",img:""},
{b:"minna1",l:12,jp:"近い",rd:"ちかい",ro:"chikai",en:"near",ru:"близкий",hy:"մոտ",img:""},
{b:"minna1",l:12,jp:"遠い",rd:"とおい",ro:"tooi",en:"far",ru:"далёкий",hy:"հեռու",img:""},
{b:"minna1",l:12,jp:"速い",rd:"はやい",ro:"hayai",en:"fast",ru:"быстрый",hy:"արագ",img:""},
{b:"minna1",l:12,jp:"遅い",rd:"おそい",ro:"osoi",en:"slow, late",ru:"медленный, поздний",hy:"դանդաղ, ուշ",img:""},
{b:"minna1",l:12,jp:"多い",rd:"おおい",ro:"ooi",en:"many, much",ru:"много",hy:"շատ",img:""},
{b:"minna1",l:12,jp:"少ない",rd:"すくない",ro:"sukunai",en:"few, little",ru:"мало",hy:"քիչ",img:""},
{b:"minna1",l:12,jp:"暖かい",rd:"あたたかい",ro:"atatakai",en:"warm",ru:"тёплый",hy:"տաք",img:""},
{b:"minna1",l:12,jp:"涼しい",rd:"すずしい",ro:"suzushii",en:"cool",ru:"прохладный",hy:"զով",img:""},
{b:"minna1",l:12,jp:"甘い",rd:"あまい",ro:"amai",en:"sweet",ru:"сладкий",hy:"քաղցր",img:""},
{b:"minna1",l:12,jp:"辛い",rd:"からい",ro:"karai",en:"spicy, hot",ru:"острый",hy:"կծու",img:""},
{b:"minna1",l:12,jp:"重い",rd:"おもい",ro:"omoi",en:"heavy",ru:"тяжёлый",hy:"ծանր",img:""},
{b:"minna1",l:12,jp:"軽い",rd:"かるい",ro:"karui",en:"light (weight)",ru:"лёгкий",hy:"թեթև",img:""},
{b:"minna1",l:12,jp:"季節",rd:"きせつ",ro:"kisetsu",en:"season",ru:"сезон",hy:"եղանակ (տարվա)",img:""},
{b:"minna1",l:12,jp:"春",rd:"はる",ro:"haru",en:"spring",ru:"весна",hy:"գարուն",img:"spring"},
{b:"minna1",l:12,jp:"夏",rd:"なつ",ro:"natsu",en:"summer",ru:"лето",hy:"ամառ",img:"summer"},
{b:"minna1",l:12,jp:"秋",rd:"あき",ro:"aki",en:"autumn",ru:"осень",hy:"աշուն",img:"autumn"},
{b:"minna1",l:12,jp:"冬",rd:"ふゆ",ro:"fuyu",en:"winter",ru:"зима",hy:"ձմեռ",img:"winter"},
{b:"minna1",l:12,jp:"天気",rd:"てんき",ro:"tenki",en:"weather",ru:"погода",hy:"եղանակ",img:""},
{b:"minna1",l:12,jp:"雨",rd:"あめ",ro:"ame",en:"rain",ru:"дождь",hy:"անձրև",img:"rain"},
{b:"minna1",l:12,jp:"雪",rd:"ゆき",ro:"yuki",en:"snow",ru:"снег",hy:"ձյուն",img:"snow"},
{b:"minna1",l:12,jp:"ホテル",rd:"",ro:"hoteru",en:"hotel",ru:"отель",hy:"հյուրանոց",img:"hotel"},
{b:"minna1",l:12,jp:"空港",rd:"くうこう",ro:"kuukou",en:"airport",ru:"аэропорт",hy:"օդանավակայան",img:""},
{b:"minna1",l:12,jp:"海",rd:"うみ",ro:"umi",en:"sea",ru:"море",hy:"ծով",img:"sea"},
{b:"minna1",l:12,jp:"世界",rd:"せかい",ro:"sekai",en:"world",ru:"мир",hy:"աշխարհ",img:""},
{b:"minna1",l:12,jp:"祭り",rd:"まつり",ro:"matsuri",en:"festival",ru:"фестиваль",hy:"տոն, փառատոն",img:""},
{b:"minna1",l:12,jp:"一番",rd:"いちばん",ro:"ichiban",en:"most, best",ru:"самый",hy:"ամենա",img:""},
{b:"minna1",l:12,jp:"初めて",rd:"はじめて",ro:"hajimete",en:"for the first time",ru:"впервые",hy:"առաջին անգամ",img:""},
/* ---- Minna I, Lesson 13 ---- */
{b:"minna1",l:13,jp:"遊びます",rd:"あそびます",ro:"asobimasu",en:"to play, enjoy oneself",ru:"играть, развлекаться",hy:"խաղալ, զվարճանալ",img:""},
{b:"minna1",l:13,jp:"泳ぎます",rd:"およぎます",ro:"oyogimasu",en:"to swim",ru:"плавать",hy:"լողալ",img:""},
{b:"minna1",l:13,jp:"迎えます",rd:"むかえます",ro:"mukaemasu",en:"to meet, greet",ru:"встречать",hy:"դիմավորել",img:""},
{b:"minna1",l:13,jp:"疲れます",rd:"つかれます",ro:"tsukaremasu",en:"to get tired",ru:"уставать",hy:"հոգնել",img:""},
{b:"minna1",l:13,jp:"出します",rd:"だします",ro:"dashimasu",en:"to send, mail",ru:"отправлять",hy:"ուղարկել, հանել",img:""},
{b:"minna1",l:13,jp:"入ります",rd:"はいります",ro:"hairimasu",en:"to enter",ru:"входить",hy:"մտնել",img:""},
{b:"minna1",l:13,jp:"出ます",rd:"でます",ro:"demasu",en:"to leave, go out",ru:"выходить",hy:"դուրս գալ",img:""},
{b:"minna1",l:13,jp:"結婚します",rd:"けっこんします",ro:"kekkonshimasu",en:"to marry",ru:"жениться, выходить замуж",hy:"ամուսնանալ",img:""},
{b:"minna1",l:13,jp:"買い物します",rd:"かいものします",ro:"kaimonoshimasu",en:"to shop",ru:"делать покупки",hy:"գնումներ անել",img:""},
{b:"minna1",l:13,jp:"食事します",rd:"しょくじします",ro:"shokujishimasu",en:"to have a meal",ru:"обедать, кушать",hy:"ուտել, ճաշել",img:""},
{b:"minna1",l:13,jp:"散歩します",rd:"さんぽします",ro:"sanposhimasu",en:"to take a walk",ru:"гулять",hy:"զբոսնել",img:""},
{b:"minna1",l:13,jp:"大変",rd:"たいへん",ro:"taihen",en:"hard, tough",ru:"тяжело, трудно",hy:"դժվար, ծանր",img:""},
{b:"minna1",l:13,jp:"欲しい",rd:"ほしい",ro:"hoshii",en:"to want",ru:"хотеть, желать",hy:"ուզել, ցանկանալ",img:""},
{b:"minna1",l:13,jp:"広い",rd:"ひろい",ro:"hiroi",en:"spacious, wide",ru:"просторный, широкий",hy:"ընդարձակ, լայն",img:""},
{b:"minna1",l:13,jp:"狭い",rd:"せまい",ro:"semai",en:"narrow, small",ru:"тесный, узкий",hy:"նեղ, փոքր",img:""},
{b:"minna1",l:13,jp:"プール",rd:"",ro:"puuru",en:"swimming pool",ru:"бассейн",hy:"լողավազան",img:""},
{b:"minna1",l:13,jp:"川",rd:"かわ",ro:"kawa",en:"river",ru:"река",hy:"գետ",img:"river"},
{b:"minna1",l:13,jp:"美術館",rd:"びじゅつかん",ro:"bijutsukan",en:"art museum",ru:"художественный музей",hy:"արվեստի թանգարան",img:"museum"},
{b:"minna1",l:13,jp:"動物",rd:"どうぶつ",ro:"doubutsu",en:"animal",ru:"животное",hy:"կենդանի",img:""},
{b:"minna1",l:13,jp:"つり",rd:"つり",ro:"tsuri",en:"fishing",ru:"рыбалка",hy:"ձկնորսություն",img:""},
{b:"minna1",l:13,jp:"スキー",rd:"",ro:"sukii",en:"skiing",ru:"катание на лыжах",hy:"դահուկ",img:"skiing"},
{b:"minna1",l:13,jp:"週末",rd:"しゅうまつ",ro:"shuumatsu",en:"weekend",ru:"выходные",hy:"շաբաթավերջ",img:""},
{b:"minna1",l:13,jp:"正月",rd:"しょうがつ",ro:"shougatsu",en:"New Year",ru:"Новый год",hy:"Ամանոր",img:""},
{b:"minna1",l:13,jp:"ほかに",rd:"ほかに",ro:"hokani",en:"besides, in addition",ru:"кроме того",hy:"բացի այդ",img:""},
/* ---- Minna I, Lesson 14 ---- */
{b:"minna1",l:14,jp:"つけます",rd:"つけます",ro:"tsukemasu",en:"to turn on",ru:"включать",hy:"միացնել",img:""},
{b:"minna1",l:14,jp:"消します",rd:"けします",ro:"keshimasu",en:"to turn off, erase",ru:"выключать, стирать",hy:"անջատել, ջնջել",img:""},
{b:"minna1",l:14,jp:"開けます",rd:"あけます",ro:"akemasu",en:"to open",ru:"открывать",hy:"բացել",img:""},
{b:"minna1",l:14,jp:"閉めます",rd:"しめます",ro:"shimemasu",en:"to close",ru:"закрывать",hy:"փակել",img:""},
{b:"minna1",l:14,jp:"急ぎます",rd:"いそぎます",ro:"isogimasu",en:"to hurry",ru:"спешить",hy:"շտապել",img:""},
{b:"minna1",l:14,jp:"待ちます",rd:"まちます",ro:"machimasu",en:"to wait",ru:"ждать",hy:"սպասել",img:""},
{b:"minna1",l:14,jp:"止めます",rd:"とめます",ro:"tomemasu",en:"to stop, park",ru:"останавливать, парковать",hy:"կանգնեցնել, կայանել",img:""},
{b:"minna1",l:14,jp:"曲がります",rd:"まがります",ro:"magarimasu",en:"to turn",ru:"поворачивать",hy:"թեքվել",img:""},
{b:"minna1",l:14,jp:"持ちます",rd:"もちます",ro:"mochimasu",en:"to hold, carry",ru:"держать, нести",hy:"բռնել, կրել",img:""},
{b:"minna1",l:14,jp:"取ります",rd:"とります",ro:"torimasu",en:"to take, pass",ru:"брать, передавать",hy:"վերցնել, փոխանցել",img:""},
{b:"minna1",l:14,jp:"手伝います",rd:"てつだいます",ro:"tetsudaimasu",en:"to help",ru:"помогать",hy:"օգնել",img:""},
{b:"minna1",l:14,jp:"呼びます",rd:"よびます",ro:"yobimasu",en:"to call",ru:"звать, вызывать",hy:"կանչել",img:""},
{b:"minna1",l:14,jp:"話します",rd:"はなします",ro:"hanashimasu",en:"to speak, talk",ru:"говорить, разговаривать",hy:"խոսել",img:""},
{b:"minna1",l:14,jp:"見せます",rd:"みせます",ro:"misemasu",en:"to show",ru:"показывать",hy:"ցույց տալ",img:""},
{b:"minna1",l:14,jp:"座ります",rd:"すわります",ro:"suwarimasu",en:"to sit down",ru:"садиться",hy:"նստել",img:""},
{b:"minna1",l:14,jp:"立ちます",rd:"たちます",ro:"tachimasu",en:"to stand up",ru:"вставать",hy:"կանգնել",img:""},
{b:"minna1",l:14,jp:"使います",rd:"つかいます",ro:"tsukaimasu",en:"to use",ru:"использовать",hy:"օգտագործել",img:""},
{b:"minna1",l:14,jp:"塩",rd:"しお",ro:"shio",en:"salt",ru:"соль",hy:"աղ",img:"salt"},
{b:"minna1",l:14,jp:"砂糖",rd:"さとう",ro:"satou",en:"sugar",ru:"сахар",hy:"շաքար",img:"sugar"},
{b:"minna1",l:14,jp:"エアコン",rd:"",ro:"eakon",en:"air conditioner",ru:"кондиционер",hy:"օդորակիչ",img:""},
{b:"minna1",l:14,jp:"名前",rd:"なまえ",ro:"namae",en:"name",ru:"имя",hy:"անուն",img:""},
{b:"minna1",l:14,jp:"住所",rd:"じゅうしょ",ro:"juusho",en:"address",ru:"адрес",hy:"հասցե",img:""},
{b:"minna1",l:14,jp:"地図",rd:"ちず",ro:"chizu",en:"map",ru:"карта",hy:"քարտեզ",img:"map"},
{b:"minna1",l:14,jp:"信号",rd:"しんごう",ro:"shingou",en:"traffic light",ru:"светофор",hy:"լուսացույց",img:""},
{b:"minna1",l:14,jp:"角",rd:"かど",ro:"kado",en:"corner",ru:"угол",hy:"անկյուն",img:""},
{b:"minna1",l:14,jp:"橋",rd:"はし",ro:"hashi",en:"bridge",ru:"мост",hy:"կամուրջ",img:""},
{b:"minna1",l:14,jp:"駐車場",rd:"ちゅうしゃじょう",ro:"chuushajou",en:"parking lot",ru:"парковка",hy:"ավտոկայանատեղ",img:""},
{b:"minna1",l:14,jp:"ゆっくり",rd:"ゆっくり",ro:"yukkuri",en:"slowly",ru:"медленно",hy:"դանդաղ",img:""},
{b:"minna1",l:14,jp:"すぐに",rd:"すぐに",ro:"suguni",en:"immediately",ru:"сразу",hy:"անմիջապես",img:""},
{b:"minna1",l:14,jp:"また",rd:"また",ro:"mata",en:"again",ru:"снова",hy:"կրկին",img:""},
/* ---- Minna I, Lesson 15 ---- */
{b:"minna1",l:15,jp:"置きます",rd:"おきます",ro:"okimasu",en:"to put, place",ru:"класть, ставить",hy:"դնել",img:""},
{b:"minna1",l:15,jp:"作ります",rd:"つくります",ro:"tsukurimasu",en:"to make",ru:"делать, создавать",hy:"պատրաստել, ստեղծել",img:""},
{b:"minna1",l:15,jp:"売ります",rd:"うります",ro:"urimasu",en:"to sell",ru:"продавать",hy:"վաճառել",img:""},
{b:"minna1",l:15,jp:"知ります",rd:"しります",ro:"shirimasu",en:"to get to know",ru:"узнавать, знать",hy:"իմանալ",img:""},
{b:"minna1",l:15,jp:"住みます",rd:"すみます",ro:"sumimasu",en:"to live, reside",ru:"жить, проживать",hy:"ապրել, բնակվել",img:""},
{b:"minna1",l:15,jp:"研究します",rd:"けんきゅうします",ro:"kenkyuushimasu",en:"to do research",ru:"исследовать",hy:"հետազոտել",img:""},
{b:"minna1",l:15,jp:"資料",rd:"しりょう",ro:"shiryou",en:"materials, data",ru:"материалы, данные",hy:"նյութեր, տվյալներ",img:""},
{b:"minna1",l:15,jp:"カタログ",rd:"",ro:"katarogu",en:"catalog",ru:"каталог",hy:"կատալոգ",img:""},
{b:"minna1",l:15,jp:"時刻表",rd:"じこくひょう",ro:"jikokuhyou",en:"timetable",ru:"расписание",hy:"չվացուցակ",img:""},
{b:"minna1",l:15,jp:"服",rd:"ふく",ro:"fuku",en:"clothes",ru:"одежда",hy:"հագուստ",img:""},
{b:"minna1",l:15,jp:"製品",rd:"せいひん",ro:"seihin",en:"product",ru:"изделие, продукт",hy:"արտադրանք",img:""},
{b:"minna1",l:15,jp:"電子辞書",rd:"でんしじしょ",ro:"denshijisho",en:"electronic dictionary",ru:"электронный словарь",hy:"էլեկտրոնային բառարան",img:""},
{b:"minna1",l:15,jp:"経済",rd:"けいざい",ro:"keizai",en:"economy",ru:"экономика",hy:"տնտեսություն",img:""},
{b:"minna1",l:15,jp:"研究者",rd:"けんきゅうしゃ",ro:"kenkyuusha",en:"researcher",ru:"исследователь",hy:"հետազոտող",img:""},
{b:"minna1",l:15,jp:"公務員",rd:"こうむいん",ro:"koumuin",en:"civil servant",ru:"государственный служащий",hy:"պետական ծառայող",img:""},
{b:"minna1",l:15,jp:"歯医者",rd:"はいしゃ",ro:"haisha",en:"dentist",ru:"стоматолог",hy:"ատամնաբույժ",img:""},
{b:"minna1",l:15,jp:"独身",rd:"どくしん",ro:"dokushin",en:"single, unmarried",ru:"холост, не женат",hy:"ամուրի",img:""},
{b:"minna1",l:15,jp:"市役所",rd:"しやくしょ",ro:"shiyakusho",en:"city hall",ru:"мэрия",hy:"քաղաքապետարան",img:"cityhall"},
/* ---- Minna I, Lesson 16 ---- */
{b:"minna1",l:16,jp:"乗ります",rd:"のります",ro:"norimasu",en:"to get on, ride",ru:"садиться (в транспорт)",hy:"նստել (փոխադրամիջոց)",img:""},
{b:"minna1",l:16,jp:"降ります",rd:"おります",ro:"orimasu",en:"to get off",ru:"выходить (из транспорта)",hy:"իջնել (փոխադրամիջոցից)",img:""},
{b:"minna1",l:16,jp:"乗り換えます",rd:"のりかえます",ro:"norikaemasu",en:"to change (trains)",ru:"пересаживаться",hy:"փոխադրվել",img:""},
{b:"minna1",l:16,jp:"浴びます",rd:"あびます",ro:"abimasu",en:"to take (a shower)",ru:"принимать (душ)",hy:"ցնցուղ ընդունել",img:""},
{b:"minna1",l:16,jp:"入れます",rd:"いれます",ro:"iremasu",en:"to put in",ru:"вкладывать, класть внутрь",hy:"ներս դնել",img:""},
{b:"minna1",l:16,jp:"押します",rd:"おします",ro:"oshimasu",en:"to push, press",ru:"нажимать",hy:"սեղմել",img:""},
{b:"minna1",l:16,jp:"卒業します",rd:"そつぎょうします",ro:"sotsugyoushimasu",en:"to graduate",ru:"заканчивать (учёбу)",hy:"ավարտել (ուսումը)",img:""},
{b:"minna1",l:16,jp:"若い",rd:"わかい",ro:"wakai",en:"young",ru:"молодой",hy:"երիտասարդ",img:""},
{b:"minna1",l:16,jp:"長い",rd:"ながい",ro:"nagai",en:"long",ru:"длинный",hy:"երկար",img:""},
{b:"minna1",l:16,jp:"短い",rd:"みじかい",ro:"mijikai",en:"short",ru:"короткий",hy:"կարճ",img:""},
{b:"minna1",l:16,jp:"明るい",rd:"あかるい",ro:"akarui",en:"bright",ru:"светлый",hy:"լուսավոր",img:""},
{b:"minna1",l:16,jp:"暗い",rd:"くらい",ro:"kurai",en:"dark",ru:"тёмный",hy:"մութ",img:""},
{b:"minna1",l:16,jp:"体",rd:"からだ",ro:"karada",en:"body",ru:"тело",hy:"մարմին",img:""},
{b:"minna1",l:16,jp:"頭",rd:"あたま",ro:"atama",en:"head",ru:"голова",hy:"գլուխ",img:"head"},
{b:"minna1",l:16,jp:"髪",rd:"かみ",ro:"kami",en:"hair",ru:"волосы",hy:"մազեր",img:"hair"},
{b:"minna1",l:16,jp:"顔",rd:"かお",ro:"kao",en:"face",ru:"лицо",hy:"դեմք",img:"face"},
{b:"minna1",l:16,jp:"目",rd:"め",ro:"me",en:"eye",ru:"глаз",hy:"աչք",img:"eye"},
{b:"minna1",l:16,jp:"耳",rd:"みみ",ro:"mimi",en:"ear",ru:"ухо",hy:"ականջ",img:"ear"},
{b:"minna1",l:16,jp:"口",rd:"くち",ro:"kuchi",en:"mouth",ru:"рот",hy:"բերան",img:"mouth"},
{b:"minna1",l:16,jp:"歯",rd:"は",ro:"ha",en:"tooth",ru:"зуб",hy:"ատամ",img:"tooth"},
{b:"minna1",l:16,jp:"足",rd:"あし",ro:"ashi",en:"foot, leg",ru:"нога",hy:"ոտք",img:"foot"},
{b:"minna1",l:16,jp:"おなか",rd:"おなか",ro:"onaka",en:"stomach, belly",ru:"живот",hy:"փոր",img:"stomach"},
{b:"minna1",l:16,jp:"どうやって",rd:"どうやって",ro:"douyatte",en:"how (in what way)",ru:"как, каким образом",hy:"ինչպես",img:""},
{b:"minna1",l:16,jp:"どの",rd:"どの",ro:"dono",en:"which",ru:"который",hy:"որ",img:""},
/* ---- Minna I, Lesson 17 ---- */
{b:"minna1",l:17,jp:"覚えます",rd:"おぼえます",ro:"oboemasu",en:"to memorize",ru:"запоминать",hy:"հիշել, անգիր անել",img:""},
{b:"minna1",l:17,jp:"忘れます",rd:"わすれます",ro:"wasuremasu",en:"to forget",ru:"забывать",hy:"մոռանալ",img:""},
{b:"minna1",l:17,jp:"なくします",rd:"なくします",ro:"nakushimasu",en:"to lose",ru:"терять",hy:"կորցնել",img:""},
{b:"minna1",l:17,jp:"払います",rd:"はらいます",ro:"haraimasu",en:"to pay",ru:"платить",hy:"վճարել",img:""},
{b:"minna1",l:17,jp:"返します",rd:"かえします",ro:"kaeshimasu",en:"to return (something)",ru:"возвращать",hy:"վերադարձնել",img:""},
{b:"minna1",l:17,jp:"出かけます",rd:"でかけます",ro:"dekakemasu",en:"to go out",ru:"выходить (из дома)",hy:"դուրս գնալ",img:""},
{b:"minna1",l:17,jp:"脱ぎます",rd:"ぬぎます",ro:"nugimasu",en:"to take off (clothes)",ru:"снимать (одежду)",hy:"հանել (հագուստ)",img:""},
{b:"minna1",l:17,jp:"心配します",rd:"しんぱいします",ro:"shinpaishimasu",en:"to worry",ru:"беспокоиться",hy:"անհանգստանալ",img:""},
{b:"minna1",l:17,jp:"残業します",rd:"ざんぎょうします",ro:"zangyoushimasu",en:"to work overtime",ru:"работать сверхурочно",hy:"արտաժամյա աշխատել",img:""},
{b:"minna1",l:17,jp:"出張します",rd:"しゅっちょうします",ro:"shucchoushimasu",en:"to go on a business trip",ru:"ехать в командировку",hy:"գործուղման գնալ",img:""},
{b:"minna1",l:17,jp:"大丈夫",rd:"だいじょうぶ",ro:"daijoubu",en:"all right, okay",ru:"всё в порядке",hy:"լավ է, ամեն ինչ կարգին է",img:""},
{b:"minna1",l:17,jp:"危ない",rd:"あぶない",ro:"abunai",en:"dangerous",ru:"опасный",hy:"վտանգավոր",img:""},
{b:"minna1",l:17,jp:"パスポート",rd:"",ro:"pasupooto",en:"passport",ru:"паспорт",hy:"անձնագիր",img:"passport"},
{b:"minna1",l:17,jp:"熱",rd:"ねつ",ro:"netsu",en:"fever",ru:"температура, жар",hy:"ջերմություն",img:""},
{b:"minna1",l:17,jp:"病気",rd:"びょうき",ro:"byouki",en:"illness",ru:"болезнь",hy:"հիվանդություն",img:""},
{b:"minna1",l:17,jp:"薬",rd:"くすり",ro:"kusuri",en:"medicine",ru:"лекарство",hy:"դեղ",img:""},
{b:"minna1",l:17,jp:"お風呂",rd:"おふろ",ro:"ofuro",en:"bath",ru:"ванна",hy:"լոգանք",img:""},
{b:"minna1",l:17,jp:"上着",rd:"うわぎ",ro:"uwagi",en:"jacket, coat",ru:"верхняя одежда, пиджак",hy:"վերարկու, բաճկոն",img:"coat"},
{b:"minna1",l:17,jp:"下着",rd:"したぎ",ro:"shitagi",en:"underwear",ru:"нижнее бельё",hy:"ներքնազգեստ",img:""},
/* ---- Minna I, Lesson 18 ---- */
{b:"minna1",l:18,jp:"できます",rd:"できます",ro:"dekimasu",en:"can, to be able to",ru:"мочь, уметь",hy:"կարողանալ",img:""},
{b:"minna1",l:18,jp:"洗います",rd:"あらいます",ro:"araimasu",en:"to wash",ru:"мыть, стирать",hy:"լվանալ",img:""},
{b:"minna1",l:18,jp:"弾きます",rd:"ひきます",ro:"hikimasu",en:"to play (instrument)",ru:"играть (на инструменте)",hy:"նվագել",img:""},
{b:"minna1",l:18,jp:"歌います",rd:"うたいます",ro:"utaimasu",en:"to sing",ru:"петь",hy:"երգել",img:""},
{b:"minna1",l:18,jp:"集めます",rd:"あつめます",ro:"atsumemasu",en:"to collect, gather",ru:"собирать, коллекционировать",hy:"հավաքել",img:""},
{b:"minna1",l:18,jp:"捨てます",rd:"すてます",ro:"sutemasu",en:"to throw away",ru:"выбрасывать",hy:"դեն նետել",img:""},
{b:"minna1",l:18,jp:"運転します",rd:"うんてんします",ro:"untenshimasu",en:"to drive",ru:"водить (машину)",hy:"վարել (մեքենա)",img:""},
{b:"minna1",l:18,jp:"予約します",rd:"よやくします",ro:"yoyakushimasu",en:"to reserve",ru:"бронировать",hy:"ամրագրել",img:""},
{b:"minna1",l:18,jp:"見学します",rd:"けんがくします",ro:"kengakushimasu",en:"to visit for study",ru:"посещать с ознакомительной целью",hy:"ուսումնական այցելություն անել",img:""},
{b:"minna1",l:18,jp:"ピアノ",rd:"",ro:"piano",en:"piano",ru:"пианино",hy:"դաշնամուր",img:"piano"},
{b:"minna1",l:18,jp:"インターネット",rd:"",ro:"intaanetto",en:"internet",ru:"интернет",hy:"ինտերնետ",img:""},
{b:"minna1",l:18,jp:"趣味",rd:"しゅみ",ro:"shumi",en:"hobby",ru:"хобби",hy:"հոբբի",img:""},
{b:"minna1",l:18,jp:"日記",rd:"にっき",ro:"nikki",en:"diary",ru:"дневник",hy:"օրագիր",img:""},
{b:"minna1",l:18,jp:"馬",rd:"うま",ro:"uma",en:"horse",ru:"лошадь",hy:"ձի",img:"horse"},
{b:"minna1",l:18,jp:"温泉",rd:"おんせん",ro:"onsen",en:"hot spring",ru:"горячий источник",hy:"տաք աղբյուր",img:"onsen"},
{b:"minna1",l:18,jp:"生け花",rd:"いけばな",ro:"ikebana",en:"flower arrangement",ru:"икебана",hy:"իկեբանա",img:"flower"},
{b:"minna1",l:18,jp:"特に",rd:"とくに",ro:"tokuni",en:"especially",ru:"особенно",hy:"հատկապես",img:""},
/* ---- Minna I, Lesson 19 ---- */
{b:"minna1",l:19,jp:"のぼります",rd:"のぼります",ro:"noborimasu",en:"to climb",ru:"подниматься, взбираться",hy:"բարձրանալ",img:""},
{b:"minna1",l:19,jp:"とまります",rd:"とまります",ro:"tomarimasu",en:"to stay (hotel)",ru:"останавливаться (в гостинице)",hy:"գիշերել, կանգ առնել",img:""},
{b:"minna1",l:19,jp:"そうじします",rd:"そうじします",ro:"soujishimasu",en:"to clean",ru:"убирать",hy:"մաքրել, հավաքել",img:""},
{b:"minna1",l:19,jp:"せんたくします",rd:"せんたくします",ro:"sentakushimasu",en:"to wash clothes",ru:"стирать",hy:"լվանալ (հագուստ)",img:""},
{b:"minna1",l:19,jp:"れんしゅうします",rd:"れんしゅうします",ro:"renshuushimasu",en:"to practice",ru:"тренироваться, упражняться",hy:"կրկնել, մարզվել",img:""},
{b:"minna1",l:19,jp:"なります",rd:"なります",ro:"narimasu",en:"to become",ru:"становиться",hy:"դառնալ",img:""},
{b:"minna1",l:19,jp:"ねむい",rd:"ねむい",ro:"nemui",en:"sleepy",ru:"сонный",hy:"քնկոտ",img:""},
{b:"minna1",l:19,jp:"つよい",rd:"つよい",ro:"tsuyoi",en:"strong",ru:"сильный",hy:"ուժեղ",img:""},
{b:"minna1",l:19,jp:"よわい",rd:"よわい",ro:"yowai",en:"weak",ru:"слабый",hy:"թույլ",img:""},
{b:"minna1",l:19,jp:"ちょうし",rd:"ちょうし",ro:"choushi",en:"condition",ru:"состояние, самочувствие",hy:"վիճակ, ինքնազգացողություն",img:""},
{b:"minna1",l:19,jp:"ゴルフ",rd:"",ro:"gorufu",en:"golf",ru:"гольф",hy:"գոլֆ",img:"golf"},
{b:"minna1",l:19,jp:"すもう",rd:"すもう",ro:"sumou",en:"sumo",ru:"сумо",hy:"սումո",img:""},
{b:"minna1",l:19,jp:"ちゃいろ",rd:"ちゃいろ",ro:"chairo",en:"brown",ru:"коричневый",hy:"շագանակագույն",img:"brown_color"},
{b:"minna1",l:19,jp:"だんだん",rd:"だんだん",ro:"dandan",en:"gradually",ru:"постепенно",hy:"աստիճանաբար",img:""},
{b:"minna1",l:19,jp:"もうすぐ",rd:"もうすぐ",ro:"mousugu",en:"soon",ru:"скоро",hy:"շուտով",img:""},
{b:"minna1",l:19,jp:"おかげさまで",rd:"おかげさまで",ro:"okagesamade",en:"thanks to you",ru:"благодаря вам",hy:"ձեր շնորհիվ",img:""},
/* ---- Minna I, Lesson 20 ---- */
{b:"minna1",l:20,jp:"いります",rd:"いります",ro:"irimasu",en:"to need",ru:"быть нужным, требоваться",hy:"պետք լինել",img:""},
{b:"minna1",l:20,jp:"しらべます",rd:"しらべます",ro:"shirabemasu",en:"to check, investigate",ru:"проверять, выяснять",hy:"ստուգել, պարզել",img:""},
{b:"minna1",l:20,jp:"なおします",rd:"なおします",ro:"naoshimasu",en:"to repair, correct",ru:"чинить, исправлять",hy:"նորոգել, ուղղել",img:""},
{b:"minna1",l:20,jp:"しゅうりします",rd:"しゅうりします",ro:"shuurishimasu",en:"to repair",ru:"ремонтировать",hy:"վերանորոգել",img:""},
{b:"minna1",l:20,jp:"ぼく",rd:"ぼく",ro:"boku",en:"I (male)",ru:"я (муж.)",hy:"ես (տղամարդու)",img:""},
{b:"minna1",l:20,jp:"きみ",rd:"きみ",ro:"kimi",en:"you (casual)",ru:"ты",hy:"դու",img:""},
{b:"minna1",l:20,jp:"ことば",rd:"ことば",ro:"kotoba",en:"word, language",ru:"слово, язык",hy:"բառ, լեզու",img:""},
{b:"minna1",l:20,jp:"きもの",rd:"きもの",ro:"kimono",en:"kimono",ru:"кимоно",hy:"կիմոնո",img:"kimono"},
{b:"minna1",l:20,jp:"ビザ",rd:"",ro:"biza",en:"visa",ru:"виза",hy:"վիզա",img:""},
{b:"minna1",l:20,jp:"はじめ",rd:"はじめ",ro:"hajime",en:"the beginning",ru:"начало",hy:"սկիզբ",img:""},
{b:"minna1",l:20,jp:"おわり",rd:"おわり",ro:"owari",en:"the end",ru:"конец",hy:"վերջ",img:""},
{b:"minna1",l:20,jp:"こっち",rd:"こっち",ro:"kocchi",en:"this way (casual)",ru:"сюда, это",hy:"այս կողմ",img:""},
{b:"minna1",l:20,jp:"そっち",rd:"そっち",ro:"socchi",en:"that way (casual)",ru:"туда, то",hy:"այդ կողմ",img:""},
{b:"minna1",l:20,jp:"あっち",rd:"あっち",ro:"acchi",en:"over there (casual)",ru:"там",hy:"այն կողմ",img:""},
{b:"minna1",l:20,jp:"どっち",rd:"どっち",ro:"docchi",en:"which (casual)",ru:"который, куда",hy:"որ կողմ, որը",img:""},
{b:"minna1",l:20,jp:"だから",rd:"だから",ro:"dakara",en:"therefore, so",ru:"поэтому",hy:"դրա համար",img:""},
/* ---- Minna I, Lesson 21 ---- */
{b:"minna1",l:21,jp:"おもいます",rd:"おもいます",ro:"omoimasu",en:"to think",ru:"думать",hy:"կարծել, մտածել",img:""},
{b:"minna1",l:21,jp:"いいます",rd:"いいます",ro:"iimasu",en:"to say",ru:"говорить, сказать",hy:"ասել",img:""},
{b:"minna1",l:21,jp:"かちます",rd:"かちます",ro:"kachimasu",en:"to win",ru:"побеждать",hy:"հաղթել",img:""},
{b:"minna1",l:21,jp:"まけます",rd:"まけます",ro:"makemasu",en:"to lose",ru:"проигрывать",hy:"պարտվել",img:""},
{b:"minna1",l:21,jp:"やくにたちます",rd:"やくにたちます",ro:"yaku ni tachimasu",en:"to be useful",ru:"быть полезным",hy:"օգտակար լինել",img:""},
{b:"minna1",l:21,jp:"うごきます",rd:"うごきます",ro:"ugokimasu",en:"to move, work (machine)",ru:"двигаться, работать (о механизме)",hy:"շարժվել, աշխատել",img:""},
{b:"minna1",l:21,jp:"やめます",rd:"やめます",ro:"yamemasu",en:"to quit, stop",ru:"бросать, прекращать",hy:"դադարեցնել, թողնել",img:""},
{b:"minna1",l:21,jp:"むだ",rd:"むだ",ro:"muda",en:"waste, useless",ru:"напрасный, бесполезный",hy:"ապարդյուն, անօգուտ",img:""},
{b:"minna1",l:21,jp:"ふべん",rd:"ふべん",ro:"fuben",en:"inconvenient",ru:"неудобный",hy:"անհարմար",img:""},
{b:"minna1",l:21,jp:"おなじ",rd:"おなじ",ro:"onaji",en:"same",ru:"одинаковый",hy:"նույն",img:""},
{b:"minna1",l:21,jp:"すごい",rd:"すごい",ro:"sugoi",en:"amazing, terrible",ru:"потрясающий, ужасный",hy:"զարմանալի, սարսափելի",img:""},
{b:"minna1",l:21,jp:"しゅしょう",rd:"しゅしょう",ro:"shushou",en:"prime minister",ru:"премьер-министр",hy:"վարչապետ",img:""},
{b:"minna1",l:21,jp:"だいとうりょう",rd:"だいとうりょう",ro:"daitouryou",en:"president (country)",ru:"президент",hy:"նախագահ",img:""},
{b:"minna1",l:21,jp:"せいじ",rd:"せいじ",ro:"seiji",en:"politics",ru:"политика",hy:"քաղաքականություն",img:""},
{b:"minna1",l:21,jp:"ニュース",rd:"",ro:"nyuusu",en:"news",ru:"новости",hy:"նորություններ",img:"news"},
{b:"minna1",l:21,jp:"スピーチ",rd:"",ro:"supiichi",en:"speech",ru:"речь, выступление",hy:"ելույթ, ճառ",img:""},
{b:"minna1",l:21,jp:"デザイン",rd:"",ro:"dezain",en:"design",ru:"дизайн",hy:"դիզայն",img:""},
{b:"minna1",l:21,jp:"こうつう",rd:"こうつう",ro:"koutsuu",en:"traffic, transport",ru:"транспорт, движение",hy:"տրանսպորտ, երթևեկություն",img:""},
{b:"minna1",l:21,jp:"かちょう",rd:"かちょう",ro:"kachou",en:"section chief",ru:"начальник отдела",hy:"բաժնի պետ",img:""},
{b:"minna1",l:21,jp:"ぶちょう",rd:"ぶちょう",ro:"buchou",en:"department head",ru:"начальник управления",hy:"վարչության պետ",img:""},
{b:"minna1",l:21,jp:"しゃちょう",rd:"しゃちょう",ro:"shachou",en:"company president",ru:"президент компании",hy:"ընկերության տնօրեն",img:""},
{b:"minna1",l:21,jp:"きっと",rd:"きっと",ro:"kitto",en:"surely, certainly",ru:"наверняка",hy:"հաստատ, անպայման",img:""},
{b:"minna1",l:21,jp:"たぶん",rd:"たぶん",ro:"tabun",en:"probably",ru:"наверное",hy:"հավանաբար",img:""},
{b:"minna1",l:21,jp:"ほんとうに",rd:"ほんとうに",ro:"hontou ni",en:"really",ru:"действительно",hy:"իսկապես",img:""},
{b:"minna1",l:21,jp:"そんなに",rd:"そんなに",ro:"sonna ni",en:"that much",ru:"настолько",hy:"այդքան",img:""},
/* ---- Minna I, Lesson 22 ---- */
{b:"minna1",l:22,jp:"きます",rd:"きます",ro:"kimasu",en:"to wear (upper body)",ru:"надевать (верхнюю одежду)",hy:"հագնել (վերին հագուստ)",img:""},
{b:"minna1",l:22,jp:"はきます",rd:"はきます",ro:"hakimasu",en:"to wear (lower body)",ru:"надевать (обувь, брюки)",hy:"հագնել (կոշիկ, տաբատ)",img:""},
{b:"minna1",l:22,jp:"かぶります",rd:"かぶります",ro:"kaburimasu",en:"to put on (head)",ru:"надевать (на голову)",hy:"դնել (գլխին)",img:""},
{b:"minna1",l:22,jp:"かけます",rd:"かけます",ro:"kakemasu",en:"to put on (glasses)",ru:"надевать (очки)",hy:"դնել (ակնոց)",img:""},
{b:"minna1",l:22,jp:"うまれます",rd:"うまれます",ro:"umaremasu",en:"to be born",ru:"рождаться",hy:"ծնվել",img:""},
{b:"minna1",l:22,jp:"コート",rd:"",ro:"kooto",en:"coat",ru:"пальто",hy:"վերարկու",img:"coat"},
{b:"minna1",l:22,jp:"セーター",rd:"",ro:"seetaa",en:"sweater",ru:"свитер",hy:"սվիտեր",img:"sweater"},
{b:"minna1",l:22,jp:"スーツ",rd:"",ro:"suutsu",en:"suit",ru:"костюм",hy:"կոստյում",img:"suit"},
{b:"minna1",l:22,jp:"ぼうし",rd:"ぼうし",ro:"boushi",en:"hat, cap",ru:"шляпа, шапка",hy:"գլխարկ",img:"hat"},
{b:"minna1",l:22,jp:"めがね",rd:"めがね",ro:"megane",en:"glasses",ru:"очки",hy:"ակնոց",img:"glasses"},
{b:"minna1",l:22,jp:"やちん",rd:"やちん",ro:"yachin",en:"rent",ru:"квартплата",hy:"վարձավճար",img:""},
{b:"minna1",l:22,jp:"けしき",rd:"けしき",ro:"keshiki",en:"scenery",ru:"пейзаж",hy:"տեսարան, բնանկար",img:""},
{b:"minna1",l:22,jp:"こまかいおかね",rd:"こまかいおかね",ro:"komakai okane",en:"small change",ru:"мелкие деньги, мелочь",hy:"մանր փող",img:""},
/* ---- Minna I, Lesson 23 ---- */
{b:"minna1",l:23,jp:"ききます",rd:"ききます",ro:"kikimasu",en:"to ask, listen",ru:"спрашивать, слушать",hy:"հարցնել, լսել",img:""},
{b:"minna1",l:23,jp:"まわします",rd:"まわします",ro:"mawashimasu",en:"to turn, rotate",ru:"крутить, поворачивать",hy:"պտտել, շրջել",img:""},
{b:"minna1",l:23,jp:"ひきます",rd:"ひきます",ro:"hikimasu",en:"to pull",ru:"тянуть",hy:"քաշել",img:""},
{b:"minna1",l:23,jp:"さわります",rd:"さわります",ro:"sawarimasu",en:"to touch",ru:"трогать, касаться",hy:"դիպչել",img:""},
{b:"minna1",l:23,jp:"うごかします",rd:"うごかします",ro:"ugokashimasu",en:"to move (something)",ru:"двигать",hy:"շարժել",img:""},
{b:"minna1",l:23,jp:"あるきます",rd:"あるきます",ro:"arukimasu",en:"to walk",ru:"идти пешком",hy:"քայլել",img:""},
{b:"minna1",l:23,jp:"わたります",rd:"わたります",ro:"watarimasu",en:"to cross",ru:"переходить",hy:"անցնել (փողոց)",img:""},
{b:"minna1",l:23,jp:"きをつけます",rd:"きをつけます",ro:"ki o tsukemasu",en:"to be careful",ru:"быть осторожным",hy:"զգույշ լինել",img:""},
{b:"minna1",l:23,jp:"ひっこしします",rd:"ひっこしします",ro:"hikkoshishimasu",en:"to move house",ru:"переезжать",hy:"տեղափոխվել",img:""},
{b:"minna1",l:23,jp:"でんきや",rd:"でんきや",ro:"denkiya",en:"electronics store",ru:"магазин электроники",hy:"էլեկտրոնիկայի խանութ",img:""},
{b:"minna1",l:23,jp:"こうさてん",rd:"こうさてん",ro:"kousaten",en:"intersection",ru:"перекрёсток",hy:"խաչմերուկ",img:""},
{b:"minna1",l:23,jp:"みち",rd:"みち",ro:"michi",en:"road, way",ru:"дорога, путь",hy:"ճանապարհ",img:""},
/* ---- Minna I, Lesson 24 ---- */
{b:"minna1",l:24,jp:"くれます",rd:"くれます",ro:"kuremasu",en:"to give (to me)",ru:"давать (мне)",hy:"տալ (ինձ)",img:""},
{b:"minna1",l:24,jp:"つれていきます",rd:"つれていきます",ro:"tsurete ikimasu",en:"to take (someone)",ru:"водить, брать с собой",hy:"տանել (մեկին)",img:""},
{b:"minna1",l:24,jp:"つれてきます",rd:"つれてきます",ro:"tsurete kimasu",en:"to bring (someone)",ru:"приводить",hy:"բերել (մեկին)",img:""},
{b:"minna1",l:24,jp:"おくります",rd:"おくります",ro:"okurimasu",en:"to escort, see off",ru:"провожать",hy:"ճանապարհել, ուղեկցել",img:""},
{b:"minna1",l:24,jp:"しょうかいします",rd:"しょうかいします",ro:"shoukaishimasu",en:"to introduce",ru:"представлять, знакомить",hy:"ներկայացնել, ծանոթացնել",img:""},
{b:"minna1",l:24,jp:"あんないします",rd:"あんないします",ro:"annaishimasu",en:"to guide, show around",ru:"показывать, сопровождать",hy:"ուղեկցել, ցույց տալ",img:""},
{b:"minna1",l:24,jp:"せつめいします",rd:"せつめいします",ro:"setsumeishimasu",en:"to explain",ru:"объяснять",hy:"բացատրել",img:""},
{b:"minna1",l:24,jp:"いれます",rd:"いれます",ro:"iremasu",en:"to make (coffee), put in",ru:"заваривать, класть внутрь",hy:"պատրաստել (սուրճ), դնել ներս",img:""},
{b:"minna1",l:24,jp:"おじいさん",rd:"おじいさん",ro:"ojiisan",en:"grandfather, old man",ru:"дедушка",hy:"պապիկ",img:"grandfather"},
{b:"minna1",l:24,jp:"おばあさん",rd:"おばあさん",ro:"obaasan",en:"grandmother, old woman",ru:"бабушка",hy:"տատիկ",img:"grandmother"},
{b:"minna1",l:24,jp:"じぶんで",rd:"じぶんで",ro:"jibun de",en:"by oneself",ru:"самостоятельно",hy:"ինքնուրույն",img:""},
/* ---- Minna I, Lesson 25 ---- */
{b:"minna1",l:25,jp:"かんがえます",rd:"かんがえます",ro:"kangaemasu",en:"to think, consider",ru:"обдумывать",hy:"մտածել, հաշվի առնել",img:""},
{b:"minna1",l:25,jp:"つきます",rd:"つきます",ro:"tsukimasu",en:"to arrive",ru:"прибывать",hy:"հասնել, ժամանել",img:""},
{b:"minna1",l:25,jp:"りゅうがくします",rd:"りゅうがくします",ro:"ryuugakushimasu",en:"to study abroad",ru:"учиться за границей",hy:"արտասահմանում սովորել",img:""},
{b:"minna1",l:25,jp:"いなか",rd:"いなか",ro:"inaka",en:"countryside, hometown",ru:"деревня, родные места",hy:"գյուղ, հայրենի վայր",img:""},
{b:"minna1",l:25,jp:"たいしかん",rd:"たいしかん",ro:"taishikan",en:"embassy",ru:"посольство",hy:"դեսպանատուն",img:"embassy"},
{b:"minna1",l:25,jp:"かいがい",rd:"かいがい",ro:"kaigai",en:"overseas",ru:"заграница",hy:"արտասահման",img:""},
{b:"minna1",l:25,jp:"きぶん",rd:"きぶん",ro:"kibun",en:"feeling, mood",ru:"настроение, самочувствие",hy:"տրամադրություն",img:""},
{b:"minna1",l:25,jp:"もし",rd:"もし",ro:"moshi",en:"if",ru:"если",hy:"եթե",img:""},
{b:"minna1",l:25,jp:"たとえば",rd:"たとえば",ro:"tatoeba",en:"for example",ru:"например",hy:"օրինակ",img:""},
{b:"minna1",l:25,jp:"おもいで",rd:"おもいで",ro:"omoide",en:"memory, recollection",ru:"воспоминание",hy:"հիշողություն",img:""},

/* ================= Minna no Nihongo II ================= */
/* ---- Lesson 26 ---- */
{b:"minna2",l:26,jp:"見ます",rd:"みます",ro:"mimasu",en:"to see (a doctor)",ru:"осматривать",hy:"զննել",img:""},
{b:"minna2",l:26,jp:"探します",rd:"さがします",ro:"sagashimasu",en:"to look for",ru:"искать",hy:"փնտրել",img:""},
{b:"minna2",l:26,jp:"遅れます",rd:"おくれます",ro:"okuremasu",en:"to be late",ru:"опаздывать",hy:"ուշանալ",img:""},
{b:"minna2",l:26,jp:"間に合います",rd:"まにあいます",ro:"maniaimasu",en:"to be in time",ru:"успевать",hy:"հասցնել",img:""},
{b:"minna2",l:26,jp:"拾います",rd:"ひろいます",ro:"hiroimasu",en:"to pick up",ru:"подбирать",hy:"վերցնել (գետնից)",img:""},
{b:"minna2",l:26,jp:"連絡します",rd:"れんらくします",ro:"renrakushimasu",en:"to contact",ru:"связываться",hy:"կապ հաստատել",img:""},
{b:"minna2",l:26,jp:"けんどう",rd:"けんどう",ro:"kendou",en:"kendo",ru:"кэндо",hy:"քենդո",img:""},
{b:"minna2",l:26,jp:"じゅうどう",rd:"じゅうどう",ro:"juudou",en:"judo",ru:"дзюдо",hy:"ձյուդո",img:"judo"},
{b:"minna2",l:26,jp:"うんどうかい",rd:"うんどうかい",ro:"undoukai",en:"sports day",ru:"спортивный праздник",hy:"մարզական օր",img:""},
{b:"minna2",l:26,jp:"フリーマーケット",rd:"",ro:"furii maaketto",en:"flea market",ru:"блошиный рынок",hy:"լու շուկա",img:""},
{b:"minna2",l:26,jp:"ばしょ",rd:"ばしょ",ro:"basho",en:"place",ru:"место",hy:"տեղ",img:""},
{b:"minna2",l:26,jp:"ボランティア",rd:"",ro:"borantia",en:"volunteer",ru:"волонтёр",hy:"կամավոր",img:""},
{b:"minna2",l:26,jp:"さいきん",rd:"さいきん",ro:"saikin",en:"recently",ru:"недавно",hy:"վերջերս",img:""},
{b:"minna2",l:26,jp:"びよういん",rd:"びよういん",ro:"biyouin",en:"beauty salon",ru:"парикмахерская",hy:"գեղեցկության սրահ",img:""},
/* ---- Lesson 27 ---- */
{b:"minna2",l:27,jp:"見えます",rd:"みえます",ro:"miemasu",en:"to be visible",ru:"быть видимым",hy:"երևալ",img:""},
{b:"minna2",l:27,jp:"聞こえます",rd:"きこえます",ro:"kikoemasu",en:"to be audible",ru:"быть слышимым",hy:"լսվել",img:""},
{b:"minna2",l:27,jp:"できます",rd:"できます",ro:"dekimasu",en:"to be built, completed",ru:"быть построенным",hy:"կառուցվել",img:""},
{b:"minna2",l:27,jp:"心配します",rd:"しんぱいします",ro:"shinpaishimasu",en:"to worry",ru:"беспокоиться",hy:"անհանգստանալ",img:""},
{b:"minna2",l:27,jp:"ペット",rd:"",ro:"petto",en:"pet",ru:"домашнее животное",hy:"ընտանի կենդանի",img:"pet"},
{b:"minna2",l:27,jp:"とり",rd:"とり",ro:"tori",en:"bird",ru:"птица",hy:"թռչուն",img:"bird"},
{b:"minna2",l:27,jp:"こえ",rd:"こえ",ro:"koe",en:"voice",ru:"голос",hy:"ձայն",img:""},
{b:"minna2",l:27,jp:"なみ",rd:"なみ",ro:"nami",en:"wave",ru:"волна",hy:"ալիք",img:"wave"},
{b:"minna2",l:27,jp:"はなび",rd:"はなび",ro:"hanabi",en:"fireworks",ru:"фейерверк",hy:"հրավառություն",img:"fireworks"},
{b:"minna2",l:27,jp:"ひるま",rd:"ひるま",ro:"hiruma",en:"daytime",ru:"дневное время",hy:"ցերեկ",img:""},
{b:"minna2",l:27,jp:"よる",rd:"よる",ro:"yoru",en:"night",ru:"ночь",hy:"գիշեր",img:""},
{b:"minna2",l:27,jp:"かなり",rd:"かなり",ro:"kanari",en:"fairly, quite",ru:"довольно",hy:"բավականին",img:""},
{b:"minna2",l:27,jp:"ぜんぶ",rd:"ぜんぶ",ro:"zenbu",en:"all",ru:"всё",hy:"ամբողջը",img:""},
{b:"minna2",l:27,jp:"ほとんど",rd:"ほとんど",ro:"hotondo",en:"almost, mostly",ru:"почти",hy:"գրեթե",img:""},
{b:"minna2",l:27,jp:"はっきり",rd:"はっきり",ro:"hakkiri",en:"clearly",ru:"ясно, чётко",hy:"հստակ",img:""},
{b:"minna2",l:27,jp:"それに",rd:"それに",ro:"soreni",en:"moreover, besides",ru:"к тому же",hy:"բացի այդ",img:""},
{b:"minna2",l:27,jp:"マンション",rd:"",ro:"manshon",en:"apartment (condominium)",ru:"многоквартирный дом",hy:"բնակարան (կոնդո)",img:""},
{b:"minna2",l:27,jp:"かていきょうし",rd:"かていきょうし",ro:"katei kyoushi",en:"private tutor",ru:"частный репетитор",hy:"մասնավոր դասատու",img:""},
/* ---- Lesson 28 ---- */
{b:"minna2",l:28,jp:"かよいます",rd:"かよいます",ro:"kayoimasu",en:"to commute",ru:"ездить (регулярно)",hy:"հաճախել",img:""},
{b:"minna2",l:28,jp:"えらびます",rd:"えらびます",ro:"erabimasu",en:"to choose",ru:"выбирать",hy:"ընտրել",img:""},
{b:"minna2",l:28,jp:"むかえます",rd:"むかえます",ro:"mukaemasu",en:"to go to meet",ru:"встречать",hy:"դիմավորել",img:""},
{b:"minna2",l:28,jp:"せいかつ",rd:"せいかつ",ro:"seikatsu",en:"life, living",ru:"жизнь, быт",hy:"կյանք, կենցաղ",img:""},
{b:"minna2",l:28,jp:"しゅうかん",rd:"しゅうかん",ro:"shuukan",en:"habit, custom",ru:"привычка",hy:"սովորույթ",img:""},
{b:"minna2",l:28,jp:"しなもの",rd:"しなもの",ro:"shinamono",en:"goods, articles",ru:"товар",hy:"ապրանք",img:""},
{b:"minna2",l:28,jp:"ねだん",rd:"ねだん",ro:"nedan",en:"price",ru:"цена",hy:"գին",img:""},
{b:"minna2",l:28,jp:"きゅうりょう",rd:"きゅうりょう",ro:"kyuuryou",en:"salary",ru:"зарплата",hy:"աշխատավարձ",img:""},
{b:"minna2",l:28,jp:"ボーナス",rd:"",ro:"boonasu",en:"bonus",ru:"премия",hy:"հավելավճար",img:""},
{b:"minna2",l:28,jp:"デート",rd:"",ro:"deeto",en:"date (romantic)",ru:"свидание",hy:"ժամադրություն",img:""},
{b:"minna2",l:28,jp:"ざんぎょう",rd:"ざんぎょう",ro:"zangyou",en:"overtime work",ru:"сверхурочная работа",hy:"արտաժամյա աշխատանք",img:""},
{b:"minna2",l:28,jp:"けんこう",rd:"けんこう",ro:"kenkou",en:"health",ru:"здоровье",hy:"առողջություն",img:""},
{b:"minna2",l:28,jp:"あんぜん",rd:"あんぜん",ro:"anzen",en:"safety, safe",ru:"безопасность",hy:"անվտանգություն",img:""},
{b:"minna2",l:28,jp:"ふとります",rd:"ふとります",ro:"futorimasu",en:"to gain weight",ru:"полнеть",hy:"գիրանալ",img:""},
{b:"minna2",l:28,jp:"やせます",rd:"やせます",ro:"yasemasu",en:"to lose weight",ru:"худеть",hy:"նիհարել",img:""},
/* ---- Lesson 29 ---- */
{b:"minna2",l:29,jp:"あきます",rd:"あきます",ro:"akimasu",en:"to open (intransitive)",ru:"открываться",hy:"բացվել",img:""},
{b:"minna2",l:29,jp:"しまります",rd:"しまります",ro:"shimarimasu",en:"to close (intransitive)",ru:"закрываться",hy:"փակվել",img:""},
{b:"minna2",l:29,jp:"つきます",rd:"つきます",ro:"tsukimasu",en:"to turn on (intransitive)",ru:"включаться",hy:"վառվել",img:""},
{b:"minna2",l:29,jp:"きえます",rd:"きえます",ro:"kiemasu",en:"to go off, disappear",ru:"гаснуть, исчезать",hy:"հանգչել, անհետանալ",img:""},
{b:"minna2",l:29,jp:"こわれます",rd:"こわれます",ro:"kowaremasu",en:"to break (intransitive)",ru:"ломаться",hy:"կոտրվել",img:""},
{b:"minna2",l:29,jp:"われます",rd:"われます",ro:"waremasu",en:"to break, crack",ru:"разбиваться",hy:"կոտրվել (ապակի)",img:""},
{b:"minna2",l:29,jp:"おれます",rd:"おれます",ro:"oremasu",en:"to break, snap",ru:"ломаться (пополам)",hy:"կոտրվել (երկուսի)",img:""},
{b:"minna2",l:29,jp:"やぶれます",rd:"やぶれます",ro:"yaburemasu",en:"to tear, get torn",ru:"рваться",hy:"պատռվել",img:""},
{b:"minna2",l:29,jp:"よごれます",rd:"よごれます",ro:"yogoremasu",en:"to become dirty",ru:"пачкаться",hy:"կեղտոտվել",img:""},
{b:"minna2",l:29,jp:"まちがえます",rd:"まちがえます",ro:"machigaemasu",en:"to make a mistake",ru:"ошибаться",hy:"սխալվել",img:""},
{b:"minna2",l:29,jp:"おとします",rd:"おとします",ro:"otoshimasu",en:"to drop",ru:"ронять",hy:"գցել",img:""},
{b:"minna2",l:29,jp:"ふくろ",rd:"ふくろ",ro:"fukuro",en:"bag, sack",ru:"пакет, мешок",hy:"տոպրակ",img:""},
{b:"minna2",l:29,jp:"さいふ",rd:"さいふ",ro:"saifu",en:"wallet",ru:"кошелёк",hy:"դրամապանակ",img:"wallet"},
{b:"minna2",l:29,jp:"えだ",rd:"えだ",ro:"eda",en:"branch",ru:"ветка",hy:"ճյուղ",img:""},
{b:"minna2",l:29,jp:"えきいん",rd:"えきいん",ro:"ekiin",en:"station employee",ru:"работник станции",hy:"կայարանի աշխատակից",img:""},
{b:"minna2",l:29,jp:"わすれもの",rd:"わすれもの",ro:"wasuremono",en:"lost/forgotten item",ru:"забытая вещь",hy:"մոռացված իր",img:""},
{b:"minna2",l:29,jp:"ごみ",rd:"ごみ",ro:"gomi",en:"garbage, trash",ru:"мусор",hy:"աղբ",img:""},
/* ---- Lesson 30 ---- */
{b:"minna2",l:30,jp:"はります",rd:"はります",ro:"harimasu",en:"to stick, paste",ru:"клеить",hy:"փակցնել",img:""},
{b:"minna2",l:30,jp:"かけます",rd:"かけます",ro:"kakemasu",en:"to hang",ru:"вешать",hy:"կախել",img:""},
{b:"minna2",l:30,jp:"かざります",rd:"かざります",ro:"kazarimasu",en:"to decorate",ru:"украшать",hy:"զարդարել",img:""},
{b:"minna2",l:30,jp:"ならべます",rd:"ならべます",ro:"narabemasu",en:"to line up, arrange",ru:"расставлять",hy:"շարել",img:""},
{b:"minna2",l:30,jp:"もどします",rd:"もどします",ro:"modoshimasu",en:"to put back, return",ru:"возвращать на место",hy:"տեղը դնել",img:""},
{b:"minna2",l:30,jp:"まとめます",rd:"まとめます",ro:"matomemasu",en:"to gather, put together",ru:"собирать, обобщать",hy:"հավաքել, ամփոփել",img:""},
{b:"minna2",l:30,jp:"よてい",rd:"よてい",ro:"yotei",en:"plan, schedule",ru:"план",hy:"ծրագիր",img:""},
{b:"minna2",l:30,jp:"つもり",rd:"つもり",ro:"tsumori",en:"intention",ru:"намерение",hy:"մտադրություն",img:""},
{b:"minna2",l:30,jp:"よやく",rd:"よやく",ro:"yoyaku",en:"reservation",ru:"бронирование",hy:"ամրագրում",img:""},
{b:"minna2",l:30,jp:"ポスター",rd:"",ro:"posutaa",en:"poster",ru:"плакат",hy:"պաստառ",img:"poster"},
{b:"minna2",l:30,jp:"カレンダー",rd:"",ro:"karendaa",en:"calendar",ru:"календарь",hy:"օրացույց",img:"calendar"},
{b:"minna2",l:30,jp:"かびん",rd:"かびん",ro:"kabin",en:"vase",ru:"ваза",hy:"ծաղկաման",img:"vase"},
{b:"minna2",l:30,jp:"ひきだし",rd:"ひきだし",ro:"hikidashi",en:"drawer",ru:"выдвижной ящик",hy:"գզրոց",img:""},
{b:"minna2",l:30,jp:"げんかん",rd:"げんかん",ro:"genkan",en:"entrance hall",ru:"прихожая",hy:"նախասրահ",img:""},
{b:"minna2",l:30,jp:"ろうか",rd:"ろうか",ro:"rouka",en:"corridor, hallway",ru:"коридор",hy:"միջանցք",img:""},
{b:"minna2",l:30,jp:"かべ",rd:"かべ",ro:"kabe",en:"wall",ru:"стена",hy:"պատ",img:""},
{b:"minna2",l:30,jp:"いけ",rd:"いけ",ro:"ike",en:"pond",ru:"пруд",hy:"լճակ",img:""},
/* ---- Lesson 31 ---- */
{b:"minna2",l:31,jp:"つづけます",rd:"つづけます",ro:"tsuzukemasu",en:"to continue",ru:"продолжать",hy:"շարունակել",img:""},
{b:"minna2",l:31,jp:"みつかります",rd:"みつかります",ro:"mitsukarimasu",en:"to be found",ru:"находиться",hy:"գտնվել",img:""},
{b:"minna2",l:31,jp:"はじまります",rd:"はじまります",ro:"hajimarimasu",en:"to begin (intransitive)",ru:"начинаться",hy:"սկսվել",img:""},
{b:"minna2",l:31,jp:"やみます",rd:"やみます",ro:"yamimasu",en:"to stop (rain)",ru:"прекращаться",hy:"դադարել",img:""},
{b:"minna2",l:31,jp:"りゅうがくします",rd:"りゅうがくします",ro:"ryuugakushimasu",en:"to study abroad",ru:"учиться за границей",hy:"արտասահմանում սովորել",img:""},
{b:"minna2",l:31,jp:"だいがくいん",rd:"だいがくいん",ro:"daigakuin",en:"graduate school",ru:"аспирантура",hy:"ասպիրանտուրա",img:""},
{b:"minna2",l:31,jp:"ぶんがく",rd:"ぶんがく",ro:"bungaku",en:"literature",ru:"литература",hy:"գրականություն",img:""},
{b:"minna2",l:31,jp:"けいざい",rd:"けいざい",ro:"keizai",en:"economics",ru:"экономика",hy:"տնտեսագիտություն",img:""},
{b:"minna2",l:31,jp:"ほうりつ",rd:"ほうりつ",ro:"houritsu",en:"law",ru:"право, закон",hy:"իրավունք, օրենք",img:""},
{b:"minna2",l:31,jp:"けんきゅう",rd:"けんきゅう",ro:"kenkyuu",en:"research",ru:"исследование",hy:"հետազոտություն",img:""},
{b:"minna2",l:31,jp:"きゅうか",rd:"きゅうか",ro:"kyuuka",en:"holiday, day off",ru:"отпуск, выходной",hy:"արձակուրդ",img:""},
{b:"minna2",l:31,jp:"ばんぐみ",rd:"ばんぐみ",ro:"bangumi",en:"(TV/radio) program",ru:"передача",hy:"հաղորդում",img:""},
{b:"minna2",l:31,jp:"てんきよほう",rd:"てんきよほう",ro:"tenki yohou",en:"weather forecast",ru:"прогноз погоды",hy:"եղանակի կանխատեսում",img:""},
{b:"minna2",l:31,jp:"にゅうがくしけん",rd:"にゅうがくしけん",ro:"nyuugaku shiken",en:"entrance exam",ru:"вступительный экзамен",hy:"ընդունելության քննություն",img:""},
/* ---- Lesson 32 ---- */
{b:"minna2",l:32,jp:"うんどうします",rd:"うんどうします",ro:"undoushimasu",en:"to exercise",ru:"заниматься спортом",hy:"մարզվել",img:""},
{b:"minna2",l:32,jp:"せいこうします",rd:"せいこうします",ro:"seikoushimasu",en:"to succeed",ru:"добиться успеха",hy:"հաջողության հասնել",img:""},
{b:"minna2",l:32,jp:"すべります",rd:"すべります",ro:"suberimasu",en:"to slip, slide",ru:"скользить",hy:"սահել",img:""},
{b:"minna2",l:32,jp:"ころびます",rd:"ころびます",ro:"korobimasu",en:"to fall down",ru:"падать",hy:"ընկնել",img:""},
{b:"minna2",l:32,jp:"けがをします",rd:"けがをします",ro:"kega o shimasu",en:"to get injured",ru:"получить травму",hy:"վնասվածք ստանալ",img:""},
{b:"minna2",l:32,jp:"かぜをひきます",rd:"かぜをひきます",ro:"kaze o hikimasu",en:"to catch a cold",ru:"простудиться",hy:"մրսել",img:""},
{b:"minna2",l:32,jp:"むり",rd:"むり",ro:"muri",en:"unreasonable, impossible",ru:"невозможный, чрезмерный",hy:"անհնարին, չափազանց",img:""},
{b:"minna2",l:32,jp:"じゅうぶん",rd:"じゅうぶん",ro:"juubun",en:"enough, sufficient",ru:"достаточно",hy:"բավարար",img:""},
{b:"minna2",l:32,jp:"おかしい",rd:"おかしい",ro:"okashii",en:"strange, funny",ru:"странный, смешной",hy:"տարօրինակ, ծիծաղելի",img:""},
{b:"minna2",l:32,jp:"うで",rd:"うで",ro:"ude",en:"arm",ru:"рука (от плеча)",hy:"բազուկ",img:"arm"},
{b:"minna2",l:32,jp:"きんにく",rd:"きんにく",ro:"kinniku",en:"muscle",ru:"мышца",hy:"մկան",img:"muscle"},
{b:"minna2",l:32,jp:"ちから",rd:"ちから",ro:"chikara",en:"strength, power",ru:"сила",hy:"ուժ",img:""},
{b:"minna2",l:32,jp:"ストレス",rd:"",ro:"sutoresu",en:"stress",ru:"стресс",hy:"սթրես",img:""},
{b:"minna2",l:32,jp:"インフルエンザ",rd:"",ro:"infuruenza",en:"influenza, flu",ru:"грипп",hy:"գրիպ",img:""},
{b:"minna2",l:32,jp:"やけど",rd:"やけど",ro:"yakedo",en:"burn (injury)",ru:"ожог",hy:"այրվածք",img:""},
/* ---- Lesson 33 ---- */
{b:"minna2",l:33,jp:"にげます",rd:"にげます",ro:"nigemasu",en:"to run away, escape",ru:"убегать",hy:"փախչել",img:""},
{b:"minna2",l:33,jp:"さわぎます",rd:"さわぎます",ro:"sawagimasu",en:"to make noise",ru:"шуметь",hy:"աղմկել",img:""},
{b:"minna2",l:33,jp:"あきらめます",rd:"あきらめます",ro:"akiramemasu",en:"to give up",ru:"сдаваться, отказываться",hy:"հրաժարվել",img:""},
{b:"minna2",l:33,jp:"投げます",rd:"なげます",ro:"nagemasu",en:"to throw",ru:"бросать",hy:"նետել",img:""},
{b:"minna2",l:33,jp:"守ります",rd:"まもります",ro:"mamorimasu",en:"to protect, keep (a promise)",ru:"защищать, соблюдать",hy:"պաշտպանել, պահպանել",img:""},
{b:"minna2",l:33,jp:"注意します",rd:"ちゅういします",ro:"chuui shimasu",en:"to be careful, warn",ru:"быть осторожным, предупреждать",hy:"զգույշ լինել, զգուշացնել",img:""},
{b:"minna2",l:33,jp:"伝えます",rd:"つたえます",ro:"tsutaemasu",en:"to convey (a message)",ru:"передавать (сообщение)",hy:"փոխանցել (հաղորդագրություն)",img:""},
{b:"minna2",l:33,jp:"注文します",rd:"ちゅうもんします",ro:"chuumon shimasu",en:"to order",ru:"заказывать",hy:"պատվիրել",img:""},
{b:"minna2",l:33,jp:"だめ",rd:"だめ",ro:"dame",en:"no good, not allowed",ru:"нельзя, никуда не годится",hy:"չի կարելի",img:""},
{b:"minna2",l:33,jp:"急",rd:"きゅう",ro:"kyuu",en:"sudden, urgent",ru:"срочный, внезапный",hy:"հրատապ, հանկարծակի",img:""},
{b:"minna2",l:33,jp:"ボタン",rd:"",ro:"botan",en:"button",ru:"кнопка, пуговица",hy:"կոճակ",img:""},
{b:"minna2",l:33,jp:"火事",rd:"かじ",ro:"kaji",en:"fire",ru:"пожар",hy:"հրդեհ",img:""},
{b:"minna2",l:33,jp:"地震",rd:"じしん",ro:"jishin",en:"earthquake",ru:"землетрясение",hy:"երկրաշարժ",img:""},
{b:"minna2",l:33,jp:"危険",rd:"きけん",ro:"kiken",en:"danger",ru:"опасность",hy:"վտանգ",img:""},
{b:"minna2",l:33,jp:"入口",rd:"いりぐち",ro:"iriguchi",en:"entrance",ru:"вход",hy:"մուտք",img:""},
{b:"minna2",l:33,jp:"出口",rd:"でぐち",ro:"deguchi",en:"exit",ru:"выход",hy:"ելք",img:""},
{b:"minna2",l:33,jp:"非常口",rd:"ひじょうぐち",ro:"hijouguchi",en:"emergency exit",ru:"запасной выход",hy:"վթարային ելք",img:""},
{b:"minna2",l:33,jp:"無料",rd:"むりょう",ro:"muryou",en:"free of charge",ru:"бесплатно",hy:"անվճար",img:""},
/* ---- Lesson 34 ---- */
{b:"minna2",l:34,jp:"みがきます",rd:"みがきます",ro:"migakimasu",en:"to brush, polish",ru:"чистить, полировать",hy:"մաքրել, փայլեցնել",img:""},
{b:"minna2",l:34,jp:"組み立てます",rd:"くみたてます",ro:"kumitatemasu",en:"to assemble",ru:"собирать (конструкцию)",hy:"հավաքել (կառուցել)",img:""},
{b:"minna2",l:34,jp:"折ります",rd:"おります",ro:"orimasu",en:"to fold, break",ru:"складывать, ломать",hy:"ծալել, կոտրել",img:""},
{b:"minna2",l:34,jp:"混ぜます",rd:"まぜます",ro:"mazemasu",en:"to mix",ru:"смешивать",hy:"խառնել",img:""},
{b:"minna2",l:34,jp:"塩",rd:"しお",ro:"shio",en:"salt",ru:"соль",hy:"աղ",img:"salt"},
{b:"minna2",l:34,jp:"砂糖",rd:"さとう",ro:"satou",en:"sugar",ru:"сахар",hy:"շաքար",img:"sugar"},
{b:"minna2",l:34,jp:"酢",rd:"す",ro:"su",en:"vinegar",ru:"уксус",hy:"քացախ",img:"vinegar"},
{b:"minna2",l:34,jp:"しょうゆ",rd:"しょうゆ",ro:"shouyu",en:"soy sauce",ru:"соевый соус",hy:"սոյայի սոուս",img:"soysauce"},
{b:"minna2",l:34,jp:"みそ",rd:"みそ",ro:"miso",en:"miso",ru:"мисо",hy:"միսո",img:"miso"},
{b:"minna2",l:34,jp:"ケーキ",rd:"",ro:"keeki",en:"cake",ru:"торт, пирожное",hy:"տորթ",img:"cake"},
{b:"minna2",l:34,jp:"うどん",rd:"うどん",ro:"udon",en:"udon noodles",ru:"удон (лапша)",hy:"ուդոն (արիշտա)",img:"noodles"},
{b:"minna2",l:34,jp:"番号",rd:"ばんごう",ro:"bangou",en:"number",ru:"номер",hy:"համար",img:""},
{b:"minna2",l:34,jp:"線",rd:"せん",ro:"sen",en:"line",ru:"линия",hy:"գիծ",img:""},
{b:"minna2",l:34,jp:"矢印",rd:"やじるし",ro:"yajirushi",en:"arrow (sign)",ru:"стрелка (знак)",hy:"սլաք (նշան)",img:""},
{b:"minna2",l:34,jp:"じゃんけん",rd:"じゃんけん",ro:"janken",en:"rock-paper-scissors",ru:"камень-ножницы-бумага",hy:"քար-մկրատ-թուղթ",img:""},
/* ---- Lesson 35 ---- */
{b:"minna2",l:35,jp:"咲きます",rd:"さきます",ro:"sakimasu",en:"to bloom",ru:"цвести",hy:"ծաղկել",img:""},
{b:"minna2",l:35,jp:"変わります",rd:"かわります",ro:"kawarimasu",en:"to change",ru:"меняться",hy:"փոխվել",img:""},
{b:"minna2",l:35,jp:"困ります",rd:"こまります",ro:"komarimasu",en:"to be troubled",ru:"быть в затруднении",hy:"դժվարության մեջ լինել",img:""},
{b:"minna2",l:35,jp:"つかまえます",rd:"つかまえます",ro:"tsukamaemasu",en:"to catch, seize",ru:"ловить, хватать",hy:"բռնել",img:""},
{b:"minna2",l:35,jp:"付き合います",rd:"つきあいます",ro:"tsukiaimasu",en:"to keep company",ru:"общаться",hy:"շփվել, ընկերակցել",img:""},
{b:"minna2",l:35,jp:"正しい",rd:"ただしい",ro:"tadashii",en:"correct",ru:"правильный",hy:"ճիշտ",img:""},
{b:"minna2",l:35,jp:"珍しい",rd:"めずらしい",ro:"mezurashii",en:"rare, unusual",ru:"редкий, необычный",hy:"հազվագյուտ",img:""},
{b:"minna2",l:35,jp:"適当",rd:"てきとう",ro:"tekitou",en:"suitable, appropriate",ru:"подходящий",hy:"հարմար",img:""},
{b:"minna2",l:35,jp:"星",rd:"ほし",ro:"hoshi",en:"star",ru:"звезда",hy:"աստղ",img:"star"},
{b:"minna2",l:35,jp:"月",rd:"つき",ro:"tsuki",en:"moon",ru:"луна",hy:"լուսին",img:"moon"},
{b:"minna2",l:35,jp:"地球",rd:"ちきゅう",ro:"chikyuu",en:"the earth",ru:"Земля (планета)",hy:"Երկիր (մոլորակ)",img:""},
{b:"minna2",l:35,jp:"太陽",rd:"たいよう",ro:"taiyou",en:"the sun",ru:"солнце",hy:"արև",img:""},
{b:"minna2",l:35,jp:"西",rd:"にし",ro:"nishi",en:"west",ru:"запад",hy:"արևմուտք",img:""},
{b:"minna2",l:35,jp:"東",rd:"ひがし",ro:"higashi",en:"east",ru:"восток",hy:"արևելք",img:""},
{b:"minna2",l:35,jp:"南",rd:"みなみ",ro:"minami",en:"south",ru:"юг",hy:"հարավ",img:""},
{b:"minna2",l:35,jp:"北",rd:"きた",ro:"kita",en:"north",ru:"север",hy:"հյուսիս",img:""},
{b:"minna2",l:35,jp:"泥棒",rd:"どろぼう",ro:"dorobou",en:"thief, burglar",ru:"вор",hy:"գող",img:""},
{b:"minna2",l:35,jp:"警官",rd:"けいかん",ro:"keikan",en:"police officer",ru:"полицейский",hy:"ոստիկան",img:""},
/* ---- Lesson 36 ---- */
{b:"minna2",l:36,jp:"慣れます",rd:"なれます",ro:"naremasu",en:"to get used to",ru:"привыкать",hy:"վարժվել",img:""},
{b:"minna2",l:36,jp:"貯めます",rd:"ためます",ro:"tamemasu",en:"to save (money)",ru:"копить (деньги)",hy:"գումար կուտակել",img:""},
{b:"minna2",l:36,jp:"直します",rd:"なおします",ro:"naoshimasu",en:"to fix, correct",ru:"чинить, исправлять",hy:"ուղղել, նորոգել",img:""},
{b:"minna2",l:36,jp:"届きます",rd:"とどきます",ro:"todokimasu",en:"to reach, arrive",ru:"доходить, достигать",hy:"հասնել (առաքվել)",img:""},
{b:"minna2",l:36,jp:"確かめます",rd:"たしかめます",ro:"tashikamemasu",en:"to make sure, confirm",ru:"убеждаться, проверять",hy:"համոզվել, ստուգել",img:""},
{b:"minna2",l:36,jp:"経験します",rd:"けいけんします",ro:"keiken shimasu",en:"to experience",ru:"иметь опыт",hy:"փորձել",img:""},
{b:"minna2",l:36,jp:"合格します",rd:"ごうかくします",ro:"goukaku shimasu",en:"to pass (an exam)",ru:"сдать (экзамен)",hy:"հանձնել (քննություն)",img:""},
{b:"minna2",l:36,jp:"太ります",rd:"ふとります",ro:"futorimasu",en:"to gain weight",ru:"полнеть",hy:"գիրանալ",img:""},
{b:"minna2",l:36,jp:"やせます",rd:"やせます",ro:"yasemasu",en:"to lose weight",ru:"худеть",hy:"նիհարել",img:""},
{b:"minna2",l:36,jp:"健康",rd:"けんこう",ro:"kenkou",en:"health",ru:"здоровье",hy:"առողջություն",img:""},
{b:"minna2",l:36,jp:"筋肉",rd:"きんにく",ro:"kinniku",en:"muscle",ru:"мышца",hy:"մկան",img:"muscle"},
{b:"minna2",l:36,jp:"ダイエット",rd:"",ro:"daietto",en:"diet",ru:"диета",hy:"դիետա",img:""},
{b:"minna2",l:36,jp:"日記",rd:"にっき",ro:"nikki",en:"diary",ru:"дневник",hy:"օրագիր",img:""},
{b:"minna2",l:36,jp:"祈ります",rd:"いのります",ro:"inorimasu",en:"to pray",ru:"молиться",hy:"աղոթել",img:""},
{b:"minna2",l:36,jp:"ため",rd:"ため",ro:"tame",en:"for the sake of",ru:"ради, для",hy:"համար",img:""},
/* ---- Lesson 37 ---- */
{b:"minna2",l:37,jp:"ほめます",rd:"ほめます",ro:"homemasu",en:"to praise",ru:"хвалить",hy:"գովել",img:""},
{b:"minna2",l:37,jp:"叱ります",rd:"しかります",ro:"shikarimasu",en:"to scold",ru:"ругать",hy:"կշտամբել",img:""},
{b:"minna2",l:37,jp:"招待します",rd:"しょうたいします",ro:"shoutai shimasu",en:"to invite",ru:"приглашать",hy:"հրավիրել",img:""},
{b:"minna2",l:37,jp:"頼みます",rd:"たのみます",ro:"tanomimasu",en:"to ask, request",ru:"просить",hy:"խնդրել",img:""},
{b:"minna2",l:37,jp:"盗みます",rd:"ぬすみます",ro:"nusumimasu",en:"to steal",ru:"красть",hy:"գողանալ",img:""},
{b:"minna2",l:37,jp:"踏みます",rd:"ふみます",ro:"fumimasu",en:"to step on",ru:"наступать",hy:"կոխել",img:""},
{b:"minna2",l:37,jp:"壊します",rd:"こわします",ro:"kowashimasu",en:"to break",ru:"ломать",hy:"կոտրել",img:""},
{b:"minna2",l:37,jp:"汚します",rd:"よごします",ro:"yogoshimasu",en:"to make dirty",ru:"пачкать",hy:"կեղտոտել",img:""},
{b:"minna2",l:37,jp:"輸出します",rd:"ゆしゅつします",ro:"yushutsu shimasu",en:"to export",ru:"экспортировать",hy:"արտահանել",img:""},
{b:"minna2",l:37,jp:"輸入します",rd:"ゆにゅうします",ro:"yunyuu shimasu",en:"to import",ru:"импортировать",hy:"ներմուծել",img:""},
{b:"minna2",l:37,jp:"翻訳します",rd:"ほんやくします",ro:"honyaku shimasu",en:"to translate",ru:"переводить",hy:"թարգմանել",img:""},
{b:"minna2",l:37,jp:"発明します",rd:"はつめいします",ro:"hatsumei shimasu",en:"to invent",ru:"изобретать",hy:"գյուտ անել",img:""},
{b:"minna2",l:37,jp:"発見します",rd:"はっけんします",ro:"hakken shimasu",en:"to discover",ru:"открывать, обнаруживать",hy:"հայտնաբերել",img:""},
{b:"minna2",l:37,jp:"設計します",rd:"せっけいします",ro:"sekkei shimasu",en:"to design",ru:"проектировать",hy:"նախագծել",img:""},
{b:"minna2",l:37,jp:"犯人",rd:"はんにん",ro:"hannin",en:"criminal, culprit",ru:"преступник",hy:"հանցագործ",img:""},
{b:"minna2",l:37,jp:"米",rd:"こめ",ro:"kome",en:"rice (uncooked)",ru:"рис (сырой)",hy:"բրինձ (հում)",img:"rice"},
{b:"minna2",l:37,jp:"麦",rd:"むぎ",ro:"mugi",en:"wheat, barley",ru:"пшеница, ячмень",hy:"ցորեն, գարի",img:""},
{b:"minna2",l:37,jp:"石油",rd:"せきゆ",ro:"sekiyu",en:"oil, petroleum",ru:"нефть",hy:"նավթ",img:""},
{b:"minna2",l:37,jp:"原料",rd:"げんりょう",ro:"genryou",en:"raw material",ru:"сырьё",hy:"հումք",img:""},
/* ---- Lesson 38 ---- */
{b:"minna2",l:38,jp:"育てます",rd:"そだてます",ro:"sodatemasu",en:"to raise, bring up",ru:"растить, воспитывать",hy:"մեծացնել, դաստիարակել",img:""},
{b:"minna2",l:38,jp:"運びます",rd:"はこびます",ro:"hakobimasu",en:"to carry",ru:"переносить",hy:"տեղափոխել",img:""},
{b:"minna2",l:38,jp:"片づけます",rd:"かたづけます",ro:"katazukemasu",en:"to tidy up",ru:"убирать, приводить в порядок",hy:"կարգի բերել, հավաքել",img:""},
{b:"minna2",l:38,jp:"見つけます",rd:"みつけます",ro:"mitsukemasu",en:"to find",ru:"находить",hy:"գտնել",img:""},
{b:"minna2",l:38,jp:"払い戻します",rd:"はらいもどします",ro:"haraimodoshimasu",en:"to refund",ru:"возвращать деньги",hy:"գումարը վերադարձնել",img:""},
{b:"minna2",l:38,jp:"整理します",rd:"せいりします",ro:"seiri shimasu",en:"to arrange, sort out",ru:"сортировать",hy:"դասավորել, կարգավորել",img:""},
{b:"minna2",l:38,jp:"貯金します",rd:"ちょきんします",ro:"chokin shimasu",en:"to save money",ru:"откладывать деньги",hy:"գումար խնայել",img:""},
{b:"minna2",l:38,jp:"引き出します",rd:"ひきだします",ro:"hikidashimasu",en:"to withdraw (money)",ru:"снимать (деньги)",hy:"գումար հանել",img:""},
{b:"minna2",l:38,jp:"通帳",rd:"つうちょう",ro:"tsuuchou",en:"bankbook, passbook",ru:"сберкнижка",hy:"խնայողական գրքույկ",img:""},
{b:"minna2",l:38,jp:"暗証番号",rd:"あんしょうばんごう",ro:"anshou bangou",en:"PIN number",ru:"ПИН-код",hy:"PIN կոդ",img:""},
{b:"minna2",l:38,jp:"習慣",rd:"しゅうかん",ro:"shuukan",en:"habit, custom",ru:"привычка, обычай",hy:"սովորույթ",img:""},
{b:"minna2",l:38,jp:"性格",rd:"せいかく",ro:"seikaku",en:"character, personality",ru:"характер",hy:"բնավորություն",img:""},
{b:"minna2",l:38,jp:"癖",rd:"くせ",ro:"kuse",en:"habit, quirk",ru:"привычка (дурная)",hy:"սովորություն (վատ)",img:""},
{b:"minna2",l:38,jp:"財布",rd:"さいふ",ro:"saifu",en:"wallet",ru:"кошелёк",hy:"դրամապանակ",img:"wallet"},
{b:"minna2",l:38,jp:"部長",rd:"ぶちょう",ro:"buchou",en:"department manager",ru:"начальник отдела",hy:"բաժնի պետ",img:""},
{b:"minna2",l:38,jp:"課長",rd:"かちょう",ro:"kachou",en:"section chief",ru:"начальник секции",hy:"բաժանմունքի պետ",img:""},
/* ---- Lesson 39 ---- */
{b:"minna2",l:39,jp:"倒れます",rd:"たおれます",ro:"taoremasu",en:"to fall down, collapse",ru:"падать, рушиться",hy:"ընկնել, փլվել",img:""},
{b:"minna2",l:39,jp:"亡くなります",rd:"なくなります",ro:"nakunarimasu",en:"to pass away, die",ru:"скончаться",hy:"մահանալ",img:""},
{b:"minna2",l:39,jp:"驚きます",rd:"おどろきます",ro:"odorokimasu",en:"to be surprised",ru:"удивляться",hy:"զարմանալ",img:""},
{b:"minna2",l:39,jp:"びっくりします",rd:"びっくりします",ro:"bikkuri shimasu",en:"to be startled",ru:"пугаться, поражаться",hy:"ցնցվել, զարմանալ",img:""},
{b:"minna2",l:39,jp:"がっかりします",rd:"がっかりします",ro:"gakkari shimasu",en:"to be disappointed",ru:"разочаровываться",hy:"հիասթափվել",img:""},
{b:"minna2",l:39,jp:"安心します",rd:"あんしんします",ro:"anshin shimasu",en:"to be relieved",ru:"успокаиваться",hy:"հանգստանալ",img:""},
{b:"minna2",l:39,jp:"けんかします",rd:"けんかします",ro:"kenka shimasu",en:"to quarrel, fight",ru:"ссориться",hy:"վիճել",img:""},
{b:"minna2",l:39,jp:"離婚します",rd:"りこんします",ro:"rikon shimasu",en:"to divorce",ru:"разводиться",hy:"ամուսնալուծվել",img:""},
{b:"minna2",l:39,jp:"泣きます",rd:"なきます",ro:"nakimasu",en:"to cry",ru:"плакать",hy:"լաց լինել",img:""},
{b:"minna2",l:39,jp:"笑います",rd:"わらいます",ro:"waraimasu",en:"to laugh",ru:"смеяться",hy:"ծիծաղել",img:""},
{b:"minna2",l:39,jp:"込みます",rd:"こみます",ro:"komimasu",en:"to be crowded",ru:"быть переполненным",hy:"լեփ-լեցուն լինել",img:""},
{b:"minna2",l:39,jp:"事故",rd:"じこ",ro:"jiko",en:"accident",ru:"авария, происшествие",hy:"վթար",img:""},
{b:"minna2",l:39,jp:"台風",rd:"たいふう",ro:"taifuu",en:"typhoon",ru:"тайфун",hy:"թայֆուն",img:""},
{b:"minna2",l:39,jp:"津波",rd:"つなみ",ro:"tsunami",en:"tsunami",ru:"цунами",hy:"ցունամի",img:""},
{b:"minna2",l:39,jp:"戦争",rd:"せんそう",ro:"sensou",en:"war",ru:"война",hy:"պատերազմ",img:""},
{b:"minna2",l:39,jp:"渋滞",rd:"じゅうたい",ro:"juutai",en:"traffic jam",ru:"пробка (на дороге)",hy:"խցանում",img:""},
{b:"minna2",l:39,jp:"急行",rd:"きゅうこう",ro:"kyuukou",en:"express (train)",ru:"экспресс (поезд)",hy:"արագընթաց (գնացք)",img:"train"},
/* ---- Lesson 40 ---- */
{b:"minna2",l:40,jp:"数えます",rd:"かぞえます",ro:"kazoemasu",en:"to count",ru:"считать",hy:"հաշվել",img:""},
{b:"minna2",l:40,jp:"確かめます",rd:"たしかめます",ro:"tashikamemasu",en:"to confirm",ru:"проверять, убеждаться",hy:"ստուգել, հաստատել",img:""},
{b:"minna2",l:40,jp:"はかります",rd:"はかります",ro:"hakarimasu",en:"to measure",ru:"измерять",hy:"չափել",img:""},
{b:"minna2",l:40,jp:"出します",rd:"だします",ro:"dashimasu",en:"to hand in, submit",ru:"сдавать, подавать",hy:"հանձնել",img:""},
{b:"minna2",l:40,jp:"連絡します",rd:"れんらくします",ro:"renraku shimasu",en:"to contact",ru:"связываться",hy:"կապվել",img:""},
{b:"minna2",l:40,jp:"喧嘩",rd:"けんか",ro:"kenka",en:"quarrel, fight",ru:"ссора",hy:"վեճ, կռիվ",img:""},
{b:"minna2",l:40,jp:"試合",rd:"しあい",ro:"shiai",en:"match, game",ru:"матч",hy:"մրցում, խաղ",img:""},
{b:"minna2",l:40,jp:"意味",rd:"いみ",ro:"imi",en:"meaning",ru:"значение",hy:"իմաստ",img:""},
{b:"minna2",l:40,jp:"締め切り",rd:"しめきり",ro:"shimekiri",en:"deadline",ru:"крайний срок",hy:"վերջնաժամկետ",img:""},
{b:"minna2",l:40,jp:"点",rd:"てん",ro:"ten",en:"score, point",ru:"балл, очко",hy:"միավոր",img:""},
{b:"minna2",l:40,jp:"どうやって",rd:"どうやって",ro:"dou yatte",en:"how (in what way)",ru:"как, каким образом",hy:"ինչպես",img:""},
/* ---- Lesson 41 ---- */
{b:"minna2",l:41,jp:"いただきます",rd:"いただきます",ro:"itadakimasu",en:"to receive (humble)",ru:"получать (скромно)",hy:"ստանալ (խոնարհ)",img:""},
{b:"minna2",l:41,jp:"くださいます",rd:"くださいます",ro:"kudasaimasu",en:"to give (to me, honorific)",ru:"давать мне (вежливо)",hy:"տալ ինձ (հարգալից)",img:""},
{b:"minna2",l:41,jp:"やります",rd:"やります",ro:"yarimasu",en:"to give (to inferior)",ru:"давать (нижестоящему)",hy:"տալ (ցածրի)",img:""},
{b:"minna2",l:41,jp:"助けます",rd:"たすけます",ro:"tasukemasu",en:"to help, rescue",ru:"помогать, спасать",hy:"օգնել, փրկել",img:""},
{b:"minna2",l:41,jp:"お祝い",rd:"おいわい",ro:"oiwai",en:"celebration, gift",ru:"поздравление, подарок",hy:"շնորհավորանք, նվեր",img:"gift"},
{b:"minna2",l:41,jp:"お年玉",rd:"おとしだま",ro:"otoshidama",en:"New Year's money gift",ru:"новогодний денежный подарок",hy:"Ամանորի դրամական նվեր",img:""},
{b:"minna2",l:41,jp:"お見舞い",rd:"おみまい",ro:"omimai",en:"visit to the sick",ru:"навещание больного",hy:"հիվանդի այցելություն",img:""},
{b:"minna2",l:41,jp:"孫",rd:"まご",ro:"mago",en:"grandchild",ru:"внук/внучка",hy:"թոռ",img:"grandchild"},
{b:"minna2",l:41,jp:"おじさん",rd:"おじさん",ro:"ojisan",en:"uncle",ru:"дядя",hy:"հորեղբայր/քեռի",img:"uncle"},
{b:"minna2",l:41,jp:"おばさん",rd:"おばさん",ro:"obasan",en:"aunt",ru:"тётя",hy:"հորաքույր/մորաքույր",img:"aunt"},
{b:"minna2",l:41,jp:"店員",rd:"てんいん",ro:"tenin",en:"shop clerk",ru:"продавец",hy:"վաճառող",img:""},
{b:"minna2",l:41,jp:"おもちゃ",rd:"おもちゃ",ro:"omocha",en:"toy",ru:"игрушка",hy:"խաղալիք",img:"toy"},
{b:"minna2",l:41,jp:"絵本",rd:"えほん",ro:"ehon",en:"picture book",ru:"книжка с картинками",hy:"նկարազարդ գիրք",img:"book"},
{b:"minna2",l:41,jp:"ぶどう",rd:"ぶどう",ro:"budou",en:"grapes",ru:"виноград",hy:"խաղող",img:"fruit"},
{b:"minna2",l:41,jp:"バーゲン",rd:"",ro:"baagen",en:"bargain sale",ru:"распродажа",hy:"զեղչ, վաճառք",img:""},
{b:"minna2",l:41,jp:"かわいい",rd:"かわいい",ro:"kawaii",en:"cute",ru:"милый",hy:"սիրուն",img:""},
/* ---- Lesson 42 ---- */
{b:"minna2",l:42,jp:"開きます",rd:"ひらきます",ro:"hirakimasu",en:"to open, hold (event)",ru:"открывать, проводить",hy:"բացել, անցկացնել",img:""},
{b:"minna2",l:42,jp:"入れ物",rd:"いれもの",ro:"iremono",en:"container",ru:"контейнер",hy:"տարա",img:""},
{b:"minna2",l:42,jp:"缶切り",rd:"かんきり",ro:"kankiri",en:"can opener",ru:"открывалка для консервов",hy:"կոնսերվի բացիչ",img:""},
{b:"minna2",l:42,jp:"栓抜き",rd:"せんぬき",ro:"sennuki",en:"bottle opener",ru:"открывалка для бутылок",hy:"շշի բացիչ",img:""},
{b:"minna2",l:42,jp:"ふろしき",rd:"ふろしき",ro:"furoshiki",en:"wrapping cloth",ru:"фуросики (обёрточная ткань)",hy:"փաթաթող կտոր",img:""},
{b:"minna2",l:42,jp:"日時",rd:"にちじ",ro:"nichiji",en:"date and time",ru:"дата и время",hy:"ամսաթիվ և ժամ",img:""},
{b:"minna2",l:42,jp:"温度",rd:"おんど",ro:"ondo",en:"temperature",ru:"температура",hy:"ջերմաստիճան",img:""},
{b:"minna2",l:42,jp:"血",rd:"ち",ro:"chi",en:"blood",ru:"кровь",hy:"արյուն",img:"blood"},
{b:"minna2",l:42,jp:"アルコール",rd:"",ro:"arukooru",en:"alcohol",ru:"алкоголь, спирт",hy:"ալկոհոլ, սպիրտ",img:""},
{b:"minna2",l:42,jp:"消費税",rd:"しょうひぜい",ro:"shouhizei",en:"consumption tax",ru:"налог на потребление",hy:"սպառման հարկ",img:""},
{b:"minna2",l:42,jp:"給料",rd:"きゅうりょう",ro:"kyuuryou",en:"salary",ru:"зарплата",hy:"աշխատավարձ",img:""},
{b:"minna2",l:42,jp:"目的",rd:"もくてき",ro:"mokuteki",en:"purpose",ru:"цель",hy:"նպատակ",img:""},
{b:"minna2",l:42,jp:"弁護士",rd:"べんごし",ro:"bengoshi",en:"lawyer",ru:"адвокат",hy:"փաստաբան",img:""},
{b:"minna2",l:42,jp:"通訳",rd:"つうやく",ro:"tsuuyaku",en:"interpreter",ru:"переводчик (устный)",hy:"թարգմանիչ (բանավոր)",img:""},
/* ---- Lesson 43 ---- */
{b:"minna2",l:43,jp:"増えます",rd:"ふえます",ro:"fuemasu",en:"to increase",ru:"увеличиваться",hy:"ավելանալ",img:""},
{b:"minna2",l:43,jp:"減ります",rd:"へります",ro:"herimasu",en:"to decrease",ru:"уменьшаться",hy:"նվազել",img:""},
{b:"minna2",l:43,jp:"上がります",rd:"あがります",ro:"agarimasu",en:"to rise, go up",ru:"подниматься",hy:"բարձրանալ",img:""},
{b:"minna2",l:43,jp:"下がります",rd:"さがります",ro:"sagarimasu",en:"to fall, go down",ru:"опускаться",hy:"իջնել",img:""},
{b:"minna2",l:43,jp:"落ちます",rd:"おちます",ro:"ochimasu",en:"to fall, drop",ru:"падать",hy:"ընկնել",img:""},
{b:"minna2",l:43,jp:"切れます",rd:"きれます",ro:"kiremasu",en:"to run out, be cut",ru:"кончаться, обрываться",hy:"վերջանալ, կտրվել",img:""},
{b:"minna2",l:43,jp:"取れます",rd:"とれます",ro:"toremasu",en:"to come off",ru:"отваливаться",hy:"պոկվել",img:""},
{b:"minna2",l:43,jp:"故障します",rd:"こしょうします",ro:"koshou shimasu",en:"to break down",ru:"ломаться (о технике)",hy:"փչանալ (տեխնիկա)",img:""},
{b:"minna2",l:43,jp:"うまく",rd:"うまく",ro:"umaku",en:"well, skillfully",ru:"хорошо, умело",hy:"լավ, հմտորեն",img:""},
{b:"minna2",l:43,jp:"枝",rd:"えだ",ro:"eda",en:"branch",ru:"ветка",hy:"ճյուղ",img:""},
{b:"minna2",l:43,jp:"紐",rd:"ひも",ro:"himo",en:"string, cord",ru:"верёвка, шнур",hy:"լար, պարան",img:""},
{b:"minna2",l:43,jp:"寂しい",rd:"さびしい",ro:"sabishii",en:"lonely",ru:"одинокий",hy:"միայնակ, տխուր",img:""},
/* ---- Lesson 44 ---- */
{b:"minna2",l:44,jp:"あやまります",rd:"あやまります",ro:"ayamarimasu",en:"to apologize",ru:"извиняться",hy:"ներողություն խնդրել",img:""},
{b:"minna2",l:44,jp:"沸かします",rd:"わかします",ro:"wakashimasu",en:"to boil (water)",ru:"кипятить",hy:"եռացնել (ջուր)",img:""},
{b:"minna2",l:44,jp:"混みます",rd:"こみます",ro:"komimasu",en:"to be crowded",ru:"быть переполненным",hy:"լեփ-լեցուն լինել",img:""},
{b:"minna2",l:44,jp:"乾かします",rd:"かわかします",ro:"kawakashimasu",en:"to dry",ru:"сушить",hy:"չորացնել",img:""},
{b:"minna2",l:44,jp:"のど",rd:"のど",ro:"nodo",en:"throat",ru:"горло",hy:"կոկորդ",img:"throat"},
{b:"minna2",l:44,jp:"爪",rd:"つめ",ro:"tsume",en:"nail (finger)",ru:"ноготь",hy:"եղունգ",img:""},
{b:"minna2",l:44,jp:"量",rd:"りょう",ro:"ryou",en:"quantity, amount",ru:"количество",hy:"քանակ",img:""},
{b:"minna2",l:44,jp:"味",rd:"あじ",ro:"aji",en:"taste, flavor",ru:"вкус",hy:"համ",img:""},
{b:"minna2",l:44,jp:"濃い",rd:"こい",ro:"koi",en:"strong, thick (taste/color)",ru:"крепкий, густой",hy:"թունդ, խիտ",img:""},
{b:"minna2",l:44,jp:"薄い",rd:"うすい",ro:"usui",en:"weak, thin, light",ru:"слабый, тонкий",hy:"թույլ, բարակ",img:""},
{b:"minna2",l:44,jp:"厚い",rd:"あつい",ro:"atsui",en:"thick",ru:"толстый",hy:"հաստ",img:""},
{b:"minna2",l:44,jp:"細かい",rd:"こまかい",ro:"komakai",en:"small, detailed, fine",ru:"мелкий, подробный",hy:"մանր, մանրամասն",img:""},
/* ---- Lesson 45 ---- */
{b:"minna2",l:45,jp:"確認します",rd:"かくにんします",ro:"kakunin shimasu",en:"to confirm, check",ru:"подтверждать, проверять",hy:"հաստատել, ստուգել",img:""},
{b:"minna2",l:45,jp:"暮らします",rd:"くらします",ro:"kurashimasu",en:"to live, get by",ru:"жить, существовать",hy:"ապրել, գոյատևել",img:""},
{b:"minna2",l:45,jp:"知らせます",rd:"しらせます",ro:"shirasemasu",en:"to inform, notify",ru:"сообщать",hy:"տեղեկացնել",img:""},
{b:"minna2",l:45,jp:"うそをつきます",rd:"うそをつきます",ro:"uso o tsukimasu",en:"to tell a lie",ru:"лгать",hy:"ստել",img:""},
{b:"minna2",l:45,jp:"文句を言います",rd:"もんくをいいます",ro:"monku o iimasu",en:"to complain",ru:"жаловаться",hy:"բողոքել",img:""},
{b:"minna2",l:45,jp:"命",rd:"いのち",ro:"inochi",en:"life",ru:"жизнь",hy:"կյանք",img:""},
{b:"minna2",l:45,jp:"記録",rd:"きろく",ro:"kiroku",en:"record",ru:"рекорд, запись",hy:"ռեկորդ, գրառում",img:""},
{b:"minna2",l:45,jp:"レントゲン",rd:"",ro:"rentogen",en:"X-ray",ru:"рентген",hy:"ռենտգեն",img:""},
{b:"minna2",l:45,jp:"手術",rd:"しゅじゅつ",ro:"shujutsu",en:"surgery, operation",ru:"операция",hy:"վիրահատություն",img:""},
{b:"minna2",l:45,jp:"注射",rd:"ちゅうしゃ",ro:"chuusha",en:"injection",ru:"укол, инъекция",hy:"ներարկում",img:""},
{b:"minna2",l:45,jp:"正しい",rd:"ただしい",ro:"tadashii",en:"correct, right",ru:"правильный",hy:"ճիշտ",img:""},
{b:"minna2",l:45,jp:"半分",rd:"はんぶん",ro:"hanbun",en:"half",ru:"половина",hy:"կես",img:""},
{b:"minna2",l:45,jp:"間違い",rd:"まちがい",ro:"machigai",en:"mistake",ru:"ошибка",hy:"սխալ",img:""},
/* ---- Lesson 46 ---- */
{b:"minna2",l:46,jp:"寄ります",rd:"よります",ro:"yorimasu",en:"to drop by",ru:"заходить, заглядывать",hy:"կողքով անցնել, մտնել",img:""},
{b:"minna2",l:46,jp:"届きます",rd:"とどきます",ro:"todokimasu",en:"to be delivered, reach",ru:"доходить, быть доставленным",hy:"հասնել, առաքվել",img:""},
{b:"minna2",l:46,jp:"帰り",rd:"かえり",ro:"kaeri",en:"way home, return",ru:"обратный путь",hy:"վերադարձ",img:""},
{b:"minna2",l:46,jp:"サイズ",rd:"",ro:"saizu",en:"size",ru:"размер",hy:"չափս",img:""},
{b:"minna2",l:46,jp:"以内",rd:"いない",ro:"inai",en:"within",ru:"в пределах",hy:"ներսում, սահմաններում",img:""},
{b:"minna2",l:46,jp:"ちょうど",rd:"ちょうど",ro:"choudo",en:"exactly, just",ru:"как раз, ровно",hy:"ճիշտ, հենց",img:""},
{b:"minna2",l:46,jp:"今ごろ",rd:"いまごろ",ro:"imagoro",en:"around this time",ru:"примерно сейчас",hy:"հիմա, այս պահին",img:""},
{b:"minna2",l:46,jp:"さっき",rd:"さっき",ro:"sakki",en:"a short while ago",ru:"недавно, только что",hy:"քիչ առաջ",img:""},
{b:"minna2",l:46,jp:"後で",rd:"あとで",ro:"atode",en:"later",ru:"позже, потом",hy:"հետո",img:""},
{b:"minna2",l:46,jp:"最終",rd:"さいしゅう",ro:"saishuu",en:"last (train, etc.)",ru:"последний (поезд и т.п.)",hy:"վերջին",img:""},
/* ---- Lesson 47 ---- */
{b:"minna2",l:47,jp:"集まります",rd:"あつまります",ro:"atsumarimasu",en:"to gather (intransitive)",ru:"собираться",hy:"հավաքվել",img:""},
{b:"minna2",l:47,jp:"別れます",rd:"わかれます",ro:"wakaremasu",en:"to separate, part",ru:"расставаться",hy:"բաժանվել, հրաժեշտ տալ",img:""},
{b:"minna2",l:47,jp:"婚約します",rd:"こんやくします",ro:"konyaku shimasu",en:"to get engaged",ru:"обручаться",hy:"նշանվել",img:""},
{b:"minna2",l:47,jp:"流行",rd:"りゅうこう",ro:"ryuukou",en:"fashion, trend",ru:"мода, тренд",hy:"նորաձևություն",img:""},
{b:"minna2",l:47,jp:"事故",rd:"じこ",ro:"jiko",en:"accident",ru:"авария, несчастный случай",hy:"վթար, պատահար",img:""},
{b:"minna2",l:47,jp:"におい",rd:"におい",ro:"nioi",en:"smell",ru:"запах",hy:"հոտ",img:""},
{b:"minna2",l:47,jp:"男性",rd:"だんせい",ro:"dansei",en:"man, male",ru:"мужчина",hy:"տղամարդ",img:"man"},
{b:"minna2",l:47,jp:"女性",rd:"じょせい",ro:"josei",en:"woman, female",ru:"женщина",hy:"կին",img:"woman"},
{b:"minna2",l:47,jp:"別々に",rd:"べつべつに",ro:"betsubetsu ni",en:"separately",ru:"по отдельности",hy:"առանձին-առանձին",img:""},
{b:"minna2",l:47,jp:"確か",rd:"たしか",ro:"tashika",en:"if I remember correctly",ru:"кажется, если не ошибаюсь",hy:"եթե չեմ սխալվում",img:""},
{b:"minna2",l:47,jp:"熱",rd:"ねつ",ro:"netsu",en:"fever",ru:"жар, температура",hy:"ջերմություն",img:""},
{b:"minna2",l:47,jp:"咳",rd:"せき",ro:"seki",en:"cough",ru:"кашель",hy:"հազ",img:""},
/* ---- Lesson 48 ---- */
{b:"minna2",l:48,jp:"降ろします",rd:"おろします",ro:"oroshimasu",en:"to let (someone) off, unload",ru:"высаживать, выгружать",hy:"իջեցնել, բեռնաթափել",img:""},
{b:"minna2",l:48,jp:"届けます",rd:"とどけます",ro:"todokemasu",en:"to deliver",ru:"доставлять",hy:"հասցնել, առաքել",img:""},
{b:"minna2",l:48,jp:"知らせます",rd:"しらせます",ro:"shirasemasu",en:"to inform",ru:"сообщать",hy:"տեղեկացնել",img:""},
{b:"minna2",l:48,jp:"習います",rd:"ならいます",ro:"naraimasu",en:"to learn",ru:"учить, изучать",hy:"սովորել",img:""},
{b:"minna2",l:48,jp:"やめます",rd:"やめます",ro:"yamemasu",en:"to quit, stop",ru:"бросать, прекращать",hy:"թողնել, դադարեցնել",img:""},
{b:"minna2",l:48,jp:"塾",rd:"じゅく",ro:"juku",en:"cram school",ru:"частная школа (репетиторская)",hy:"լրացուցիչ դասընթացների դպրոց",img:""},
{b:"minna2",l:48,jp:"生徒",rd:"せいと",ro:"seito",en:"pupil, student",ru:"ученик",hy:"աշակերտ",img:"student"},
{b:"minna2",l:48,jp:"食費",rd:"しょくひ",ro:"shokuhi",en:"food expenses",ru:"расходы на еду",hy:"սննդի ծախս",img:""},
{b:"minna2",l:48,jp:"娘",rd:"むすめ",ro:"musume",en:"daughter",ru:"дочь",hy:"դուստր",img:"daughter"},
{b:"minna2",l:48,jp:"息子",rd:"むすこ",ro:"musuko",en:"son",ru:"сын",hy:"որդի",img:"son"},
{b:"minna2",l:48,jp:"荷物",rd:"にもつ",ro:"nimotsu",en:"luggage, baggage",ru:"багаж, вещи",hy:"ուղեբեռ, բեռ",img:"luggage"},
{b:"minna2",l:48,jp:"英会話",rd:"えいかいわ",ro:"eikaiwa",en:"English conversation",ru:"разговорный английский",hy:"անգլերեն խոսակցություն",img:""},
{b:"minna2",l:48,jp:"以上",rd:"いじょう",ro:"ijou",en:"more than, that's all",ru:"более, свыше; на этом всё",hy:"ավելի, ավել; վերջ",img:""},
/* ---- Lesson 49 ---- */
{b:"minna2",l:49,jp:"過ごします",rd:"すごします",ro:"sugoshimasu",en:"to spend (time)",ru:"проводить (время)",hy:"անցկացնել (ժամանակ)",img:""},
{b:"minna2",l:49,jp:"いらっしゃいます",rd:"いらっしゃいます",ro:"irasshaimasu",en:"to be, come, go (honorific)",ru:"быть, приходить, идти (вежливо)",hy:"լինել, գալ, գնալ (հարգալից)",img:""},
{b:"minna2",l:49,jp:"召し上がります",rd:"めしあがります",ro:"meshiagarimasu",en:"to eat, drink (honorific)",ru:"есть, пить (вежливо)",hy:"ուտել, խմել (հարգալից)",img:""},
{b:"minna2",l:49,jp:"おっしゃいます",rd:"おっしゃいます",ro:"osshaimasu",en:"to say (honorific)",ru:"говорить (вежливо)",hy:"ասել (հարգալից)",img:""},
{b:"minna2",l:49,jp:"なさいます",rd:"なさいます",ro:"nasaimasu",en:"to do (honorific)",ru:"делать (вежливо)",hy:"անել (հարգալից)",img:""},
{b:"minna2",l:49,jp:"ご覧になります",rd:"ごらんになります",ro:"goran ni narimasu",en:"to see, look (honorific)",ru:"смотреть (вежливо)",hy:"նայել (հարգալից)",img:""},
{b:"minna2",l:49,jp:"ご存じです",rd:"ごぞんじです",ro:"gozonji desu",en:"to know (honorific)",ru:"знать (вежливо)",hy:"իմանալ (հարգալից)",img:""},
{b:"minna2",l:49,jp:"重役",rd:"じゅうやく",ro:"juuyaku",en:"executive, director",ru:"руководитель, директор",hy:"ղեկավար, տնօրեն",img:""},
{b:"minna2",l:49,jp:"お客様",rd:"おきゃくさま",ro:"okyakusama",en:"guest, customer (polite)",ru:"гость, клиент (вежливо)",hy:"հյուր, հաճախորդ (քաղաքավարի)",img:""},
{b:"minna2",l:49,jp:"教授",rd:"きょうじゅ",ro:"kyouju",en:"professor",ru:"профессор",hy:"պրոֆեսոր",img:""},
{b:"minna2",l:49,jp:"欠席",rd:"けっせき",ro:"kesseki",en:"absence",ru:"отсутствие, непосещение",hy:"բացակայություն",img:""},
{b:"minna2",l:49,jp:"結構",rd:"けっこう",ro:"kekkou",en:"fine, no thank you",ru:"хорошо; достаточно, спасибо",hy:"լավ; բավական է",img:""},
/* ---- Lesson 50 ---- */
{b:"minna2",l:50,jp:"参ります",rd:"まいります",ro:"mairimasu",en:"to come, go (humble)",ru:"приходить, идти (скромно)",hy:"գալ, գնալ (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"おります",rd:"おります",ro:"orimasu",en:"to be (humble)",ru:"быть, находиться (скромно)",hy:"լինել, գտնվել (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"申します",rd:"もうします",ro:"moushimasu",en:"to say, be called (humble)",ru:"говорить, называться (скромно)",hy:"ասել, կոչվել (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"いたします",rd:"いたします",ro:"itashimasu",en:"to do (humble)",ru:"делать (скромно)",hy:"անել (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"拝見します",rd:"はいけんします",ro:"haiken shimasu",en:"to see, look (humble)",ru:"смотреть (скромно)",hy:"նայել (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"存じます",rd:"ぞんじます",ro:"zonjimasu",en:"to know, think (humble)",ru:"знать, думать (скромно)",hy:"իմանալ, մտածել (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"伺います",rd:"うかがいます",ro:"ukagaimasu",en:"to ask, visit (humble)",ru:"спрашивать, навещать (скромно)",hy:"հարցնել, այցելել (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"お目にかかります",rd:"おめにかかります",ro:"ome ni kakarimasu",en:"to meet (humble)",ru:"встречаться (скромно)",hy:"հանդիպել (խոնարհ)",img:""},
{b:"minna2",l:50,jp:"みなさま",rd:"みなさま",ro:"minasama",en:"everyone (polite)",ru:"все (вежливо)",hy:"բոլորդ (քաղաքավարի)",img:""},
{b:"minna2",l:50,jp:"先日",rd:"せんじつ",ro:"senjitsu",en:"the other day",ru:"на днях, недавно",hy:"օրերս, վերջերս",img:""},
{b:"minna2",l:50,jp:"さっそく",rd:"さっそく",ro:"sassoku",en:"at once, right away",ru:"сразу же, немедленно",hy:"անմիջապես, իսկույն",img:""}
);

/* re-assign stable ids across the full (now larger) list */
WORDS.forEach((w,i)=>{ w.id = w.b+"-"+w.l+"-"+i; });
